### ISSUE TITLE
Ivy server crashes when ngcc is run outside of language service

### ISSUE THREAD

**Issue by kyliau** [angular/vscode-ng-language-service#1030]
**Describe the bug**

When the extension is running, the server crashes when ngcc is run from the terminal.

**To Reproduce**

Open an Angular project, make sure Ivy language service is enabled, wait for server to be ready.
Go to terminal, run ngcc.
Server crashes.

**Expected behavior**

Running ngcc outside of extension should not crash the server.

**Logs**

```
/node_modules/@angular/language-service/bundles/ivy.js:145
            throw new Error(`Program does not contain "${fileName}" - available files are ${program.getSourceFiles().map(sf => sf.fileName).join(', ')}`);
            ^

Error: Program does not contain "/integration/project/app/app.component.ngtypecheck.ts" - available files are 
  /node_modules/typescript/lib/lib.es6.d.ts, 
  /node_modules/typescript/lib/lib.es5.d.ts, 
  /node_modules/typescript/lib/lib.es2015.d.ts, 
  /node_modules/typescript/lib/lib.dom.d.ts, 
  /node_modules/typescript/lib/lib.dom.iterable.d.ts,
  /node_modules/typescript/lib/lib.webworker.importscripts.d.ts, 
  /node_modules/typescript/lib/lib.scripthost.d.ts, 
  /node_modules/typescript/lib/lib.es2015.core.d.ts, 
  /node_modules/typescript/lib/lib.es2015.collection.d.ts,
  /node_modules/typescript/lib/lib.es2015.generator.d.ts,
  /node_modules/typescript/lib/lib.es2015.iterable.d.ts,
  /node_modules/typescript/lib/lib.es2015.promise.d.ts,
  /node_modules/typescript/lib/lib.es2015.proxy.d.ts,
  /node_modules/typescript/lib/lib.es2015.reflect.d.ts,
  /node_modules/typescript/lib/lib.es2015.symbol.d.ts,
  /node_modules/typescript/lib/lib.es2015.symbol.wellknown.d.ts,
  /integration/project/node_modules/rxjs/internal/Subscription.d.ts,
  /integration/project/node_modules/rxjs/internal/types.d.ts,
  /integration/project/node_modules/rxjs/internal/Subscriber.d.ts,
  /integration/project/node_modules/rxjs/internal/Operator.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/iif.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/throwError.d.ts,
  /integration/project/node_modules/rxjs/internal/Observable.d.ts,
  /integration/project/node_modules/rxjs/internal/Subject.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/ConnectableObservable.d.ts,
  /integration/project/node_modules/rxjs/internal/operators/groupBy.d.ts,
  /integration/project/node_modules/rxjs/internal/symbol/observable.d.ts,
  /integration/project/node_modules/rxjs/internal/BehaviorSubject.d.ts,
  /integration/project/node_modules/rxjs/internal/ReplaySubject.d.ts,
  /integration/project/node_modules/rxjs/internal/AsyncSubject.d.ts,
  /integration/project/node_modules/rxjs/internal/Scheduler.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/Action.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/AsyncScheduler.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/AsyncAction.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/AsapScheduler.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/asap.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/async.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/QueueScheduler.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/queue.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/AnimationFrameScheduler.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/animationFrame.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduler/VirtualTimeScheduler.d.ts,
  /integration/project/node_modules/rxjs/internal/Notification.d.ts,
  /integration/project/node_modules/rxjs/internal/util/pipe.d.ts,
  /integration/project/node_modules/rxjs/internal/util/noop.d.ts,
  /integration/project/node_modules/rxjs/internal/util/identity.d.ts,
  /integration/project/node_modules/rxjs/internal/util/isObservable.d.ts,
  /integration/project/node_modules/rxjs/internal/util/ArgumentOutOfRangeError.d.ts,
  /integration/project/node_modules/rxjs/internal/util/EmptyError.d.ts,
  /integration/project/node_modules/rxjs/internal/util/ObjectUnsubscribedError.d.ts,
  /integration/project/node_modules/rxjs/internal/util/UnsubscriptionError.d.ts,
  /integration/project/node_modules/rxjs/internal/util/TimeoutError.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/bindCallback.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/bindNodeCallback.d.ts,
  /integration/project/node_modules/rxjs/internal/InnerSubscriber.d.ts,
  /integration/project/node_modules/rxjs/internal/OuterSubscriber.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/combineLatest.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/concat.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/defer.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/empty.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/forkJoin.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/from.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/fromEvent.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/fromEventPattern.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/generate.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/interval.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/merge.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/never.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/of.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/onErrorResumeNext.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/pairs.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/partition.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/race.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/range.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/timer.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/using.d.ts,
  /integration/project/node_modules/rxjs/internal/observable/zip.d.ts,
  /integration/project/node_modules/rxjs/internal/scheduled/scheduled.d.ts,
  /integration/project/node_modules/rxjs/internal/config.d.ts,
  /integration/project/node_modules/rxjs/index.d.ts,
  /integration/project/node_modules/@angular/core/src/r3_symbols.d.ts,
  /integration/project/node_modules/@angular/core/core.d.ts,
  /integration/project/app/app.component.ts,
  /integration/project/node_modules/@angular/common/common.d.ts,
  /integration/project/app/foo.component.ts,
  /integration/project/app/app.module.ts,
  /integration/project/node_modules/@types/color-name/index.d.ts
    at getSourceFileOrError (/node_modules/@angular/language-service/bundles/ivy.js:145:19)
    at TemplateTypeCheckerImpl.getDiagnosticsForFile (/node_modules/@angular/language-service/bundles/ivy.js:37172:32)
    at LanguageService.getSemanticDiagnostics (/node_modules/@angular/language-service/bundles/ivy.js:39976:45)
    at Object.getSemanticDiagnostics (/node_modules/@angular/language-service/bundles/ivy.js:40151:38)
    at Session.sendPendingDiagnostics (/dist/server/session.js:228:56)
    at Timeout._onTimeout (/dist/server/session.js:213:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by kyliau** [comment]
Turns out `ngcc` is a red-herring here. The real problem lies in partial / full reload of a configured project.

When ngcc is invoked in the terminal, the language server picks up the `__ngcc_lock_file__` in `node_modules` because the server is watching the directory. By default, the server ignores certain files based on their extension, but since the lock file has no extension, it triggers the reload logic in `ProjectService`.

There are two reload modes: `Partial` and `Full`.
https://github.com/microsoft/TypeScript/blob/bec8071c65903db36864b162496ad8884a7bc6c4/src/server/project.ts#L2159-L2184

In either mode, `ProjectService` will reload the root files using the project's `tsconfig.json`.
Because the synthetic typecheck files (filenames that end with `.ngtypecheck.ts`) are not root files, they get **deleted** from the project. This operation is done here: https://github.com/microsoft/TypeScript/blob/bec8071c65903db36864b162496ad8884a7bc6c4/src/server/editorServices.ts#L2245-L2256

The crash happens when Angular compiler tries to retrieve the source file for the typecheck files but they are now gone.

So, what are our options to fix this?
1. It is unreasonable to assume the project will never reload.
2. We detect the reload event, and discard the incremental driver so that Angular compiler starts all over.
3. During a reload, right before `ProjectService` calls [`updateNonInferredProjectFiles`()](https://github.com/microsoft/TypeScript/blob/bec8071c65903db36864b162496ad8884a7bc6c4/src/server/editorServices.ts#L2190), it actually retrieves `externalFiles` so that they could be included in the `rootFilesMap`: https://github.com/microsoft/TypeScript/blob/bec8071c65903db36864b162496ad8884a7bc6c4/src/server/editorServices.ts#L2274-L2285. We could reinsert the typecheck files by implementing `getExternalFiles()`.

I'll copy the code here so that it's easier to explain what's going on ([original source](https://github.com/microsoft/TypeScript/blob/bec8071c65903db36864b162496ad8884a7bc6c4/src/server/editorServices.ts#L2274-L2285)):
```ts
        /**
         * Reload the file names from config file specs and update the project graph
         */
        /*@internal*/
        reloadFileNamesOfConfiguredProject(project: ConfiguredProject) {
            const configFileSpecs = project.getCompilerOptions().configFile!.configFileSpecs!;
            const configFileName = project.getConfigFilePath();
            const fileNames = getFileNamesFromConfigSpecs(configFileSpecs, getDirectoryPath(configFileName), project.getCompilationSettings(), project.getCachedDirectoryStructureHost(), this.hostConfiguration.extraFileExtensions);
            project.updateErrorOnNoInputFiles(fileNames);
            this.updateNonInferredProjectFiles(project, fileNames.concat(project.getExternalFiles()), fileNamePropertyReader);
            return project.updateGraph();
        }
```

(2) sounds like a reasonable approach, because it is consistent with TypeScript's behavior of reloading the project. However it increases computation because we could actually reuse the typecheck files (TS does reuse existing TS source files in the project). I also have not found a way to detect the reload event.

(3) requires us to implement `getExternalFiles()`, but the role of this method in Ivy mode is different from that in View Engine mode. In View Engine, we return a set of external HTML templates. This caused some problems because we have to make sure they are not being parsed as TS files. In Ivy mode, we return a set of existing typecheck files in the program. Since these typecheck files are TS files, the behavior is more consistent with what tsserver expects. Besides, it allows us to reuse the typecheck files.

My recommendation is (3).

**Comment by ayazhafiz** [comment]
Thanks for the great explanation @kyliau. I agree (3) sounds like the best idea.

**Comment by atscott** [comment]
Echoing @ayazhafiz's feelings exactly; thanks for the explanation and I also agree that (3) sounds like the best idea. The typecheck files seem to fit the description of "external files" that we care about so it makes sense to register them in that way.
