### ISSUE TITLE
Cannot read property 'name' of undefined

### ISSUE THREAD

**Issue by zhuweid** [angular/vscode-ng-language-service#1086]
my angular language service keeps crashing in the last few days.

The language service initializes successfully, but crashed after several minutes. 

I am using 

@angular-devkit/build-angular": "0.1000.4",
    "@angular/cli": "10.0.0",
    "@angular/compiler-cli": "10.0.0",
    "@angular/language-service": "10.0.0",
"typescript": "3.9.5"

and the latest vs code extension - v11.1.1

this is the log

[Trace - 10:49:09 am] Received notification 'textDocument/publishDiagnostics'.
c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:24511
                    if (type.symbol.name == 'TemplateRef' && isReferenceType(type)) {
                                    ^

TypeError: Cannot read property 'name' of undefined
    at TypeScriptSymbolQuery.getTemplateRefContextType (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:24511:37)
    at TypeScriptSymbolQuery.getTemplateContext (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:24478:42)
    at ExpressionDiagnosticsVisitor.visitVariable (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:23585:49)
    at VariableAst.visit (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:10341:28)
    at visit (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:10531:26)
    at c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:10533:31
    at Array.forEach (<anonymous>)
    at templateVisitAll (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:10532:14)
    at visit (c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:10518:34)
    at c:\Users\WEIDE495\.vscode\extensions\angular.ng-template-11.1.1\node_modules\@angular\language-service\bundles\language-service.js:10489:17
[Error - 10:49:09 am] Connection to server got closed. Server will not be restarted.

**Comment by kyliau** [comment]
@zhuweid could you please provide a minimal reproduction or show us the template you were working on when the crash occurred? 
Another alternative is to switch to Ivy mode, since View Engine (the one you're using above) language service will be going away soon.
See the release notes of [v11.1.1](https://github.com/angular/vscode-ng-language-service/releases/tag/v11.1.0) on how to enable Ivy.

**Comment by zhuweid** [comment]
thanks, it does fix the issue after i enabled Ivy mode.

**Comment by kyliau** [comment]
Thanks for the confirmation, I'll mark this as resolved.
