### ISSUE TITLE
Angular Language Service Crashed

### ISSUE THREAD

**Issue by Stas1967** [angular/vscode-ng-language-service#1114]
Issue Type: <b>Bug</b>

Angular Language Service
 On update to v 11.2.0 this service not work

Extension version: 11.2.0
VS Code version: Code 1.53.2 (622cb03f7e070a9670c94bae1a45d78d7181fbd4, 2021-02-11T11:48:04.245Z)
OS version: Windows_NT x64 10.0.18363

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-4720HQ CPU @ 2.60GHz (8 x 2594)|
|GPU Status|2d_canvas: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: enabled<br>opengl: enabled_on<br>protected_video_decode: unavailable_off<br>rasterization: enabled<br>skia_renderer: enabled_on<br>video_decode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|11.91GB (7.03GB free)|
|Process Argv|--crash-reporter-id 294ee2be-ebc8-4d39-8114-467944f74f95|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by vaindil** [comment]
I am having presumably the same issue. I was prompted to update to using the Ivy-based language service, I did, and VS Code is now informing me that it's crashing so much that it won't restart anymore. The console shows this error:

```
var sourceFile = program.getSourceFile(fileName);
                                     ^

TypeError: Cannot read property 'getSourceFile' of undefined
    at getValidSourceFile (c:\Repos\<snip>\node_modules\typescript\lib\tsserverlibrary.js:147054:38)
    at Object.getSemanticDiagnostics (c:\Repos\<snip>\node_modules\typescript\lib\tsserverlibrary.js:147265:36)
    at Session.sendPendingDiagnostics (c:\Users\<snip>\.vscode-insiders\extensions\angular.ng-template-11.2.0\server\index.js:1359:57)
    at Timeout._onTimeout (c:\Users\<snip>\.vscode-insiders\extensions\angular.ng-template-11.2.0\server\index.js:1344:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
```
