### ISSUE TITLE
Extension (v11.2.2) failed with error on angular 11.2.0

### ISSUE THREAD

**Issue by Valera1980** [angular/vscode-ng-language-service#1130]
Extension failed on angular 11.2.0

![image](https://user-images.githubusercontent.com/12474311/108467298-a6d71200-728d-11eb-888c-11a2795513dd.png)

![image](https://user-images.githubusercontent.com/12474311/108467138-66779400-728d-11eb-8f7d-181411067fb7.png)

******* output ************
[Info  - 8:33:57 AM] Angular language server process ID: 17001
[Info  - 8:33:57 AM] Using typescript/lib/tsserverlibrary v4.1.5 from /home/valera/.vscode/extensions/angular.ng-template-11.2.2/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 8:33:57 AM] Using @angular/language-service/bundles/ivy v11.2.1 from /home/valera/.vscode/extensions/angular.ng-template-11.2.2/node_modules/@angular/language-service/bundles/ivy.js
[Info  - 8:33:57 AM] Log file: /home/valera/.config/Code/logs/20210219T082150/exthost1/Angular.ng-template/nglangsvc.log
[Error - 8:34:24 AM] Failed to run ngcc for /mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/tsconfig.json:
    ngcc for /mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/tsconfig.json returned exit code 1, stderr: [33mWarning:[0m Entry point 'ngx-toastr' contains deep imports into '/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler/src/core'. This is probably not a problem, but may cause the compilation of entry points to be out of order.
Error: Error on worker #1: Error: Failed to find exported name of node (CommonModule = /** @class */ (function () {
    function CommonModule() {
    }
    CommonModule = __decorate([
        NgModule({
            declarations: [COMMON_DIRECTIVES, COMMON_PIPES],
            exports: [COMMON_DIRECTIVES, COMMON_PIPES],
            providers: [
                { provide: NgLocalization, useClass: NgLocaleLocalization },
            ],
        })
    ], CommonModule);
    return CommonModule;
}())) in '/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/angularx-social-login/angularx-social-login.js'.
    at Object.findExportedNameOfNode (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/find_export.js:36:19)
    at LogicalProjectStrategy.emit (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:233:38)
    at ReferenceEmitter.emit (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/imports/src/emitter.js:72:44)
    at Object.toR3Reference (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/util.js:249:31)
    at NgModuleDecoratorHandler._toR3Reference (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:416:31)
    at /mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:72
    at Array.map (<anonymous>)
    at NgModuleDecoratorHandler.analyze (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/annotations/src/ng_module.js:195:38)
    at NgccTraitCompiler.TraitCompiler.analyzeTrait (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:345:40)
    at analyze (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/src/ngtsc/transform/src/compilation.js:296:58)
    at ClusterMaster.onWorkerMessage (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:195:27)
    at /mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:55:95
    at ClusterMaster.<anonymous> (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:293:57)
    at step (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/tslib/tslib.js:143:27)
    at Object.next (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/tslib/tslib.js:124:57)
    at /mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/tslib/tslib.js:117:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/tslib/tslib.js:113:16)
    at EventEmitter.<anonymous> (/mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:287:32)
    at EventEmitter.emit (events.js:315:20)
    Language service will remain disabled.
[Info  - 8:34:24 AM] Enabling Ivy language service for /mnt/afe01ad8-a763-4688-94a9-8827ed472dfa/adsaver/AdSaver/LmsAdSaver/tsconfig.json.

**Comment by JoostK** [comment]
It appears you are using `angularx-social-login` at some `1.x` version, which is incompatible with the version of Angular you're using. There is a `3.x` version of this package available, which hopefully does work (v1.x contains all of `@angular/common` which is definitely an issue of that library that can't be addressed from Angular's side)

**Comment by Valera1980** [comment]
Hi.Thanks for answer.I'll try upgrade the package

**Comment by atscott** [comment]
Closing per Joost's comment here: https://github.com/angular/vscode-ng-language-service/issues/1130#issuecomment-782236963
