### ISSUE TITLE
TypeError: Cannot read property 'charCount' of undefined

### ISSUE THREAD

**Issue by julianobrasil** [angular/vscode-ng-language-service#127]
I think it started happening today after upgrade Angular to 4.2.6 (**not sure**).

The error ocurs after merging two branches (no errors nor conflicts in the merge process). I made 3 merges in different branches and it happened after each merge.

After the error is thrown, no more error messages are shown.

```
e:/.../src/app/restrito/administracao/aba-areas-atuantes/aba-areas-atuantes-responsabilidades/aba-areas-atuantes-responsabilidades.component.spec.ts deleted
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EPERM
    at exports._errnoException (util.js:1022:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1293:11)
[Info  - 09:13:04] Connection to server got closed. Server will restart.
Search path: e:/.../src/app/restrito/administracao/aba-configuracoes
Config file name: e:/.../src/tsconfig.json
Angular Language Service: 4.3.0-beta.0-1fc0d05
TypeScript: 2.3.4
getTemplateRefrences: 2128ms
Add recursive watcher for: e:/.../src
Opened configuration file e:/.../src/tsconfig.json
getTemplateRefrences: 0ms
SERVER ERROR: Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2449:39)
    at LineIndex.edit (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2095:39)
    at ScriptVersionCache.edit (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2051:18)
    at ScriptInfo.editContent (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:422:18)
    at LSHost.editScript (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:613:20)
    at ProjectService.clientFileChanges (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:1423:42)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:167:42
    at TextDocuments.logErrors (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:235:13)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:149:76
[Error - 09:13:11] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'charCount' of undefined
SERVER ERROR: Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2449:39)
    at LineIndex.edit (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2095:39)
    at ScriptInfo.snap (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:411:25)
    at LSHost.lineOffsetToPosition (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:658:28)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:1448:30)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:152:56
    at TextDocuments.logErrors (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:235:13)
[Error - 09:13:11] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'charCount' of undefined
SERVER ERROR: Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2449:39)
    at LineIndex.edit (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2095:39)
    at ScriptInfo.snap (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:411:25)
    at LSHost.lineOffsetToPosition (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:658:28)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:1448:30)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:152:56
    at TextDocuments.logErrors (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\documents.js:235:13)
[Error - 09:13:11] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'charCount' of undefined
C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2449
                childCharCount = child.charCount();
                                      ^

TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2449:39)
    at LineIndex.edit (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2095:39)
    at ScriptVersionCache.latestVersion (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2059:18)
    at LSHost.getScriptVersion (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:551:29)
    at TypeScriptServiceHost.getTemplateAt (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50950:67)
    at TypeScriptServiceHost.getTemplates (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50974:39)
    at LanguageServiceImpl.getDiagnostics (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:50629:35)
    at C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2696:72
    at time (C:\...\.vscode\extensions\Angular.ng-template-0.1.4\server\editorServices.js:2687:22)
[Info  - 09:13:12] Connection to server got closed. Server will restart.
```
## Setup

Microsoft Visual Code
Angular Language Service plugin 0.1.4

@angular/cli: 1.2.0
node: 6.10.3
os: win32 x64
@angular/animations: 4.2.6
@angular/cdk: 2.0.0-beta.8
@angular/common: 4.2.6
@angular/compiler: 4.2.6
@angular/compiler-cli: 4.2.6
@angular/core: 4.2.6
@angular/flex-layout: 2.0.0-beta.8
@angular/forms: 4.2.6
@angular/http: 4.2.6
@angular/material: 2.0.0-beta.8
@angular/platform-browser: 4.2.6
@angular/platform-browser-dynamic: 4.2.6
@angular/platform-server: 4.2.6
@angular/router: 4.2.6
@angular/cli: 1.2.0
@angular/language-service: 4.2.6

**Comment by thomaspink** [comment]
The error for me throws even if i am not in an angular project :/

**Comment by chuckjaz** [comment]
Closed in 0.1.6

**Comment by jtsom** [comment]
Nope, sorry. Just reported an issue where this showed for me, using 0.1.6

**Comment by chuckjaz** [comment]
@jtsom Can you attach a repro?

**Comment by nikklassen** [comment]
```
...
updating project structure from ...
getTemplateRefrences: 0ms
getTemplateRefrences: 0ms
getTemplateRefrences: 0ms
getTemplateRefrences: 0ms
updated: ng - 0ms
[Error - 8:59:37 PM] SERVER ERROR: Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:2441:35)
    at LineIndex.edit (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:2095:39)
    at ScriptInfo.snap (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:411:25)
    at LSHost.lineOffsetToPosition (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:658:28)
    at /Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:1448:30)
    at TextDocuments.getServiceInfo (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/documents.js:216:54)
    at /Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/server.js:148:24
[Error - 8:59:37 PM] Request textDocument/definition failed.
  Message: Request textDocument/definition failed with message: Cannot read property 'charCount' of undefined
  Code: -32603
[Error - 8:59:37 PM] SERVER ERROR: Cannot read property 'charCount' of undefined
TypeError: Cannot read property 'charCount' of undefined
    at LineNode.walk (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:2441:35)
    at LineIndex.edit (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:2095:39)
    at ScriptInfo.snap (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:411:25)
    at LSHost.lineOffsetToPosition (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:658:28)
    at /Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/editorServices.js:1448:30)
    at TextDocuments.getServiceInfo (/Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/documents.js:216:54)
    at /Users/nik/.vscode/extensions/Angular.ng-language-service-0.1.6/server/server.js:148:24
```

This happened when I ran a `:%s` command using the VsCodeVim extension. The occurances I was replacing were in the form `[directive]="<thing to replace>"`.  Several of these exceptions showed up.

**Comment by kyliau** [comment]
Closing this issue since it's more than two years old. Please open a new one if issue persists.
