### ISSUE TITLE
Language client is not ready yet

### ISSUE THREAD

**Issue by kozmonotselcuk** [angular/vscode-ng-language-service#129]
Language client is not ready yet: Error: Language client is not ready yet
    at LanguageClient.sendNotification (/Users/selcuk/.vscode/extensions/Angular.ng-template-0.1.4/node_modules/vscode-languageclient/lib/main.js:610:19)
    at DidChangeTextDocumentFeature.callback (/Users/selcuk/.vscode/extensions/Angular.ng-template-0.1.4/node_modules/vscode-languageclient/lib/main.js:274:34)
    at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:55860)
    at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:57651)
    at t.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:342707)
    at t.e.handle (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:308956)
    at s (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189275)
    at h (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:23:189930)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by chuckjaz** [comment]
This looks like problem in the `vscode-languageclient` client module which my plugin uses.

**Comment by kyliau** [comment]
Closing this, since issue is more than two years old.
