### ISSUE TITLE
'textDocument/didSave' failed with message: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by scote** [angular/vscode-ng-language-service#134]
I got this error on my project when i'm saving a file.

The project has Angular-CLI 1,1,1.

```
Search path: c:/git/ng2-materialize/demo-app/src/app/validation/validation-ngmodel
Config file name: c:/git/ng2-materialize/demo-app/tsconfig.json
Angular Language Service: 4.2.2
TypeScript: 2.3.4
SERVER ERROR: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at StaticSymbolResolver.resolveSymbol (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:42005:33)
    at StaticReflector.getTypeMetadata (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:41815:67)
    at StaticReflector.annotations (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:41244:55)
    at DirectiveResolver.isDirective (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:31290:61)
    at CompileMetadataResolver.isDirective (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:32254:37)
    at CompileMetadataResolver._getTypeDescriptor (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:32483:18)
    at c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:32354:78
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:32337:49)
    at addNgModule (c:\git\ng2-materialize\demo-app\node_modules\@angular\language-service\bundles\language-service.umd.js:41115:58)
[Error - 9:31:35 PM] Notification handler 'textDocument/didSave' failed with message: Cannot read property 'length' of undefined
```

**Comment by chuckjaz** [comment]
Fix in 0.1.6
