### ISSUE TITLE
Errors on deleted (renamed file)

### ISSUE THREAD

**Issue by paulaustin-automutatio** [angular/vscode-ng-language-service#1387]
# 🐞 bug report

### Is this a regression?

Never worked

### Description

ng generate component -m app to-rename

Edit the ts, html so that errors show up and save everything

Rename the ts and html to something else (e.g. renamed.ts)

Errors still show up in the problems tab with

Unable to open 'emails-field.component.html': Unable to read file '...' (Error: Unable to resolve non-existing file 'c...).

Only option is to Create file.

In this case all that is needed is that the error be removed from the Problems list as it is no longer applicable as the file doesn't exist.

In fact any kind of refactoring of typescript doesn't really work well as imports don't get updated properly either.

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

**Expected behavior**

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

</code></pre>

### **Screenshots**

![Example Screenshot](./output.png)

## 🌍  Your Environment
**Angular Version:**
<pre><code>

</code></pre>

Extension Version:
<pre><code>

</code></pre>

VSCode Version:
<pre><code>

</code></pre>

Operating System:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by snebjorn** [comment]
I'm having a similar issue renaming folders containing angular files. 
If I disable Angular Language Service in VS Code I can rename the folder. It have been a problem for a while. It started around the time where we switched to ESLint, so I thought that was the cause. But I've tracked it down to being with the Angular Language Service.

**Comment by atscott** [comment]
@snebjorn Can you provide a project to reproduce this problem with? Also, please file a new issue as it would be totally separate from this one.

**Comment by snebjorn** [comment]
done https://github.com/angular/vscode-ng-language-service/issues/1398

**Comment by atscott** [comment]
Copying from https://github.com/angular/vscode-ng-language-service/issues/1616#issuecomment-1088322989

Steps:

1. Open Angular 13 Project
2. Start development server (`ng serve`)
3. Replace a file externally, with a copy that just adds a line of code (emulates an external code generation tool)
4. "ngtsc" non-sense errors are displayed

![errors](https://user-images.githubusercontent.com/196808/161693956-49575c1b-1f0f-43d8-b500-9cb6e7662418.png)

I turned debug level to "verbose" and I see this on the "nglangsvc.log" (I replaced common_pb.d.ts externally): 

> Info 772  [8:32:8.69] A plugin threw an exception in getExternalFiles: Error: Debug Failure. False expression: getScriptInfo
Verbose Debug Information: scriptInfo for a file 'c:/XXX/src/generated/common_pb.d.ts' Path: 'c:/XXX/src/generated/common_pb.d.ts' / 'c:/XXX/src/generated/common_pb.d.ts' is missing.
Info 773  [8:32:8.90] Error: Debug Failure. False expression: getScriptInfo
Verbose Debug Information: scriptInfo for a file 'c:/XXX/src/generated/common_pb.d.ts' Path: 'c:/XXX/src/generated/common_pb.d.ts' / 'c:/XXX/src/generated/common_pb.d.ts' is missing.
    at c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164982:30
    at Object.map (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:652:29)
    at ConfiguredProject.Project.getScriptInfos (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164980:27)
    at Object.getExternalFiles (c:\Users\XXX\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\@angular\language-service\bundles\language-service.js:45477:42)
    at Object.getExternalFiles (c:\Users\XXX\.vscode\extensions\angular.ng-template-14.0.0-next.0\node_modules\@angular\language-service\index.js:27:149)
    at c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164876:46
    at Object.flatMap (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:716:25)
    at ConfiguredProject.Project.getExternalFiles (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:164872:35)
    at ProjectService.reloadFileNamesOfConfiguredProject (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:168109:86)
    at ConfiguredProject.updateGraph (c:\XXX\node_modules\typescript\lib\tsserverlibrary.js:166141:54)
