### ISSUE TITLE
Language service crashes Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined

### ISSUE THREAD

**Issue by Benny739** [angular/vscode-ng-language-service#1438]
The angular language server keeps on crashing in our nx angular project.
Switching to the legacy view engine language service solves the error.

<pre><code>
(node:33950) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'startRecordingFilesWithChangedResolutions' of undefined
    at ConfiguredProject.Project.updateGraph (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/node_modules/typescript/lib/tsserverlibrary.js:158378:38)
    at ConfiguredProject.updateGraph (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/node_modules/typescript/lib/tsserverlibrary.js:159340:63)
    at Object.updateProjectIfDirty (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/node_modules/typescript/lib/tsserverlibrary.js:159829:45)
    at ConfiguredProject.Project.getLanguageService (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/node_modules/typescript/lib/tsserverlibrary.js:157999:28)
    at Session.handleCompilerOptionsDiagnostics (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/server/index.js:3549:31)
    at Session.enableLanguageServiceForProject (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/server/index.js:3522:14)
    at Session.runNgcc (/Users/benny/.vscode/extensions/angular.ng-template-12.1.1/server/index.js:4091:14)
(node:33950) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 12.1.0
Node: 14.15.4
Package Manager: npm 7.16.0
OS: darwin x64

Angular: 12.1.0
... animations, cdk, cli, common, compiler, compiler-cli, core
... forms, language-service, material, platform-browser
... platform-browser-dynamic, pwa, router, service-worker

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1201.0
@angular-devkit/build-angular   12.1.0
@angular-devkit/core            12.1.0
@angular-devkit/schematics      12.1.0
@angular/fire                   6.1.5
@angular/flex-layout            12.0.0-beta.34
@schematics/angular             12.1.0
rxjs                            6.6.7
typescript                      4.2.4

</code></pre>

Extension Version:
<pre><code>
12.1.1

</code></pre>

VSCode Version:
<pre><code>
Version: 1.57.1
Commit: 507ce72a4466fbb27b715c3722558bb15afa9f48
Date: 2021-06-17T13:28:32.912Z
Electron: 12.0.7
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.5.0

</code></pre>

Operating System:
<pre><code>
MacOs 11.4
</code></pre>

**Comment by atscott** [comment]
@Benny739 Are you able to provide an example project that has this issue?

**Comment by atscott** [comment]
Also, would you mind trying the `12.1.0` version of the extension? I'm wondering if this could have been caused by updating the TS dependency to `4.3` that was included in the `12.1.1` release.

**Comment by Benny739** [comment]
Downgrading the version has no effect. We will try to reproduce the issue next week in our team. The crashing is very random and we have no idea what is causing it. The language service then just stops recognizing our components and marks everything red. It happens only when we're serving one or multiple of the apps in den workspace.
