### ISSUE TITLE
Crashes on encountering dodgy styles import

### ISSUE THREAD

**Issue by MattJeanes** [angular/vscode-ng-language-service#145]
So we have a legacy ASP.NET 4.5 application which unfortunately means we cannot use the webpack-dev-middleware and all the cool stuff that brings so we've stuck with our own little gulpfile/systemjs combination for that project.

The problem is where we try to import our templates/styles, it basically just crashes out with this (sanitised) error message:

```
Search path: c:/_dev/<project>/app/ITAdmin
Config file name: c:/_dev/<project>/tsconfig.json
Angular Language Service: 4.3.0-beta.0-1fc0d05
TypeScript: 2.3.4
SERVER ERROR: Expected 'styles' to be an array of strings.
Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:20894:19)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32139:13)
    at CompileMetadataResolver._getEntryComponentMetadata (C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32856:45)
    at C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32842:48
    at Array.forEach (native)
    at CompileMetadataResolver._getEntryComponentsFromProvider (C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32841:30)
    at C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32805:83
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32768:19)
    at C:\Users\<Username>\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32770:23
[Error - 13:47:21] Notification handler 'textDocument/didOpen' failed with message: Expected 'styles' to be an array of strings.
```

Here is a sample of the code causing the issue:

```typescript
import style from "./UserEdit.style.css";
import template from "./UserEdit.template.html";

@Component({
    moduleId: module.id,
    template,
    styles: [style],
})
```

We have some global typescript typings so it should know that they are strings:

```typescript
// Globals

declare var module: any;
declare var require: any;

declare module "*.css" {
    let string: string;
    export default string;
}

declare module "*.html" {
    let string: string;
    export default string;
}
```

Either way, even if this scenario is supposed to be supported or not, it's causing the language service to constantly crash and restart which is both annoying and it means we don't get any sort of intellisense in our templates or code at all.

This issue appears to be related to #85

**Comment by kyliau** [comment]
We have completely rewrote the extension, and it has fixed many fundamental issues like this.
The new extension is now live. Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. Please open a new issue for any lingering bugs, thank you!
