### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by rikan** [angular/vscode-ng-language-service#146]
Hi, I always got this error like below with ng-language-service when I saving in html files. And this extention seems to not working on my projects. My pc is windows 10, vscode is 1.15.1 and nodejs is v6.11.0.

Search path: d:/codes/cie/front-end/src/app/base/depts
Config file name: d:/codes/cie/front-end/tsconfig.json
Angular Language Service: 4.3.0-beta.0-1fc0d05
TypeScript: 2.3.4
SERVER ERROR: Maximum call stack size exceeded
RangeError: Maximum call stack size exceeded
```
at _isNgModuleMetadata (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:31643:16)
at findLast (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:31465:13)
at NgModuleResolver.resolve (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:31667:45)
at CompileMetadataResolver.getNgModuleMetadata (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32320:60)
at CompileMetadataResolver.getNgModuleSummary (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32276:52)
at C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32368:68
at Array.forEach (native)
at CompileMetadataResolver.getNgModuleMetadata (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32363:49)
at CompileMetadataResolver.getNgModuleSummary (C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32276:52)
at C:\Users\user\.vscode\extensions\Angular.ng-template-0.1.4\server\node_modules\@angular\language-service\bundles\language-service.umd.js:32368:68
```
Notification handler 'textDocument/didSave' failed with message: Maximum call stack size exceeded

**Comment by chuckjaz** [comment]
This type of reporting was moved in 0.1.6. Can verify that this is no longer a problem?

**Comment by rikan** [comment]
Great work, it's fixed and this extention is woking well on my projects.
