### ISSUE TITLE
Release problems

### ISSUE THREAD

**Issue by filiptronicek** [angular/vscode-ng-language-service#1585]
Hello to the wonderful people from the Angular team 👋!

# 🐞 bug report

### Description

The asset provided on the GitHub Releases doesn't contain the `dist/` folder, which means it cannot start the main script defined here: https://github.com/angular/vscode-ng-language-service/blob/9cdba357e0f19aab55ddcfc8283346184acab7c7/package.json#L174

## Bug Type
What does this bug affect

- [x] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

1. Download the latest release asset (https://github.com/angular/vscode-ng-language-service/releases/download/v13.1.0/ng-template-13.1.0.vsix)
2. Unarchive the file
3. Inside the now extracted folder, look into the `extension/` directory
4. Observe the absence of a `dist/` directory

**Expected behavior**

In the release process, the script / person that creates the release asset should execute
```
scripts/build.sh package.json
```

after installing dependencies and before packaging up the extension. This will result in having a built extension.

### **Logs**

Logs when trying to activate the extension now in VSC:
```
[2021-11-19 10:43:16.646] [exthost] [error] Error: Cannot find module '/Users/***/.vscode-oss/extensions/angular.ng-template-13.0.0/dist/client/extension'
Require stack:
- /Applications/VSCodium.app/Contents/Resources/app/out/vs/loader.js
- /Applications/VSCodium.app/Contents/Resources/app/out/bootstrap-amd.js
- /Applications/VSCodium.app/Contents/Resources/app/out/bootstrap-fork.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:887:15)
    at Module._load (internal/modules/cjs/loader.js:732:27)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Function.n._load (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:28606)
    at Function.b._load (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:25193)
    at Function.h._load (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:103:60406)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.r [as __$__nodeRequire] (/Applications/VSCodium.app/Contents/Resources/app/out/vs/loader.js:5:101)
    at w._loadCommonJSModule (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113:26603)
    at w._doActivateExtension (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:12894)
    at w._activateExtension (/Applications/VSCodium.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:99:11867)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async Promise.all (index 1)
```

**Comment by atscott** [comment]
Executing `scripts/build.sh package.json` _is_ part of the release process. The `vsix` we publish in the releases section is identical to the one published to the VSCode marketplace. The `dist` folder should not be in the `vsix` at all. In fact `dist/npm` contains the vsix itself.

The `package.json` in the root of this repo is not the one intended to be used for the vsix. It points to the `dist` folder for debugging purposes when running the extension host from VSCode. The `package.json` in the `extension` folder of the `vsix` has ` "main": "./index",` which points to the `index.js` in the same folder. 

This all appears correct. Is there something I'm missing here?

**Comment by atscott** [comment]
It's also worth noting that the currently published `vsix` on open-vsx.org has the same structure. That is, it's identical to what we publish in the releases section. Closing as this doesn't appear to be an issue on our end.

**Comment by filiptronicek** [comment]
Hey there @atscott, I now see how it is, thanks for responding and taking the time. I am sorry for raising this issue, I will take a look and investigate it on our end again.
