### ISSUE TITLE
Cannot read property 'isLeaf' of undefined

### ISSUE THREAD

**Issue by gonzofish** [angular/vscode-ng-language-service#169]
Version: 0.1.7
VS Code: 1.15.1 x64
OS: Windows 10

I'm getting the same error in different projects, here's a sample of the output (replaced my home directory with `%HOME%`):

```shell
[Error - 8:15:47 AM] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'isLeaf' of undefined
SERVER ERROR: Cannot read property 'isLeaf' of undefined
TypeError: Cannot read property 'isLeaf' of undefined
    at EditWalker.pre (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1990:40)
    at LineNode.execWalk (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2394:21)
    at LineNode.walk (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2458:26)
    at LineIndex.edit (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2095:39)
    at ScriptInfo.snap (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:411:25)
    at LSHost.lineOffsetToPosition (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:658:28)
    at %HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1448:30)
[Error - 8:15:47 AM] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'isLeaf' of undefined
Error for getDiagnostics:
    TypeError: Cannot read property 'isLeaf' of undefined
    at EditWalker.pre (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:1990:40)
    at LineNode.execWalk (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2394:21)
    at LineNode.walk (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2458:26)
    at LineIndex.edit (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2313:27)
    at ScriptVersionCache.getSnapshot (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2095:39)
    at ScriptVersionCache.latestVersion (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:2059:18)
    at LSHost.getScriptVersion (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\editorServices.js:551:29)
    at TypeScriptServiceHost.getTemplates (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:39133:39)
    at LanguageServiceImpl.getDiagnostics (%HOME%\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:38782:35)
```

Thanks in advance! I've been loving this plugin

**Comment by kyliau** [comment]
Closing this, since issue is more than two years old.
