### ISSUE TITLE
Language client is not ready yet: Error: Language client is**

### ISSUE THREAD

**Issue by kozmonotselcuk** [angular/vscode-ng-language-service#173]
/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:29 [Angular.ng-template] Language client is not ready yet: Error: Language client is not ready yet
	at LanguageClient.sendNotification (/Users/selcuk/.vscode/extensions/Angular.ng-template-0.1.7/node_modules/vscode-languageclient/lib/main.js:610:19)
	at DidChangeTextDocumentFeature.callback (/Users/selcuk/.vscode/extensions/Angular.ng-template-0.1.7/node_modules/vscode-languageclient/lib/main.js:274:34)
	at e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:55287)
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:57078)
	at e.$acceptModelChanged (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:348918)
	at t.e.invoke (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:423958)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280554)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:280244)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:279271
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:28:281190

**Comment by chuckjaz** [comment]
A stack trace is insufficient information for me to reproduce this problem.

Can you give me more details?

**Comment by kyliau** [comment]
The new extension is now live. Please download it from https://marketplace.visualstudio.com/items?itemName=Angular.ng-template
I'd like to close this issue for now. Please open a new issue for any lingering bugs, thank you!
