### ISSUE TITLE
Angular Language Service crashes with new project

### ISSUE THREAD

**Issue by monkey-mku** [angular/vscode-ng-language-service#1756]
### Description

When I generate a new project and open the app.component.html the extension will crash after 10-20 seconds with the message:
The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. ng new (no routing, css, no further configuration)
2. open folder in vs code
3. navigate to app.component.html

**Expected behavior**

Extension should not crash.

### **Logs**

<pre><code>
c:\Users\mku.MONKEY\.vscode\extensions\angular.ng-template-14.2.0\server\index.js:3850
            watchFile: ts.WatchFileKind.UseFsEvents,
                                        ^

TypeError: Cannot read properties of undefined (reading 'UseFsEvents')
    at Session.createProjectService (c:\Users\mku.MONKEY\.vscode\extensions\angular.ng-template-14.2.0\server\index.js:3850:41)
    at new Session (c:\Users\mku.MONKEY\.vscode\extensions\angular.ng-template-14.2.0\server\index.js:3820:36)
    at main (c:\Users\mku.MONKEY\.vscode\extensions\angular.ng-template-14.2.0\server\index.js:4739:19)
    at Object.<anonymous> (c:\Users\mku.MONKEY\.vscode\extensions\angular.ng-template-14.2.0\server\index.js:4765:1)
    at Module._compile (node:internal/modules/cjs/loader:1165:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1220:10)
    at Module.load (node:internal/modules/cjs/loader:1035:32)
    at Module._load (node:internal/modules/cjs/loader:876:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
[Error - 10:37:03] Connection to server got closed. Server will not be restarted.
</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular CLI: 14.2.3
Node: 16.13.2
Package Manager: npm 8.1.2
OS: win32 x64
</code></pre>

Extension Version:
<pre><code>
v14.2.0
</code></pre>

VSCode Version:
<pre><code>
Version: 1.71.2 (system setup)
Commit: 74b1f979648cc44d385a2286793c226e611f59e7
Date: 2022-09-14T21:03:37.738Z
Electron: 19.0.12
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
</code></pre>

Operating System:
<pre><code>
Windows 10 Version 10.0.19044 Build 19044
</code></pre>

Extension options:
<pre><code>
"angular.log": "verbose",
"angular.trace.server": "verbose",
</code></pre>

**Anything else relevant?**
I have tried setting the watch options myself in the tsconfig.json since the code it crashes on mentions that these are fallback options but that also didn't work. I have an older project (but also on angular 14) I did not create myself where the extension works but cannot figure out what causes this issue in new projects.

**Comment by monkey-mku** [comment]
Now I found out that I still had an old typescript sdk path in my user settings which caused VS Code to use an old ts version.
After removing that or manually setting the workspace to use the version installed via npm it's working again.
