### ISSUE TITLE
'textDocument/didOpen' method failed 

### ISSUE THREAD

**Issue by Corsseir** [angular/vscode-ng-language-service#176]
```
Search path: /home/corsseir/Documents/Projects/translate/frontend/translate/src/app/media-player
Config file name: /home/corsseir/Documents/Projects/translate/frontend/translate/tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2
SERVER ERROR: watch /home/corsseir/Documents/Projects/translate/frontend/translate/e2e ENOSPC
Error: watch /home/corsseir/Documents/Projects/translate/frontend/translate/e2e ENOSPC
    at exports._errnoException (util.js:1050:11)
    at FSWatcher.start (fs.js:1410:19)
    at Object.fs.watch (fs.js:1436:11)
    at addDirWatcher (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3724:35)
    at Object.addFile (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3734:21)
    at Object.watchFile (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3893:60)
    at ProjectServiceHostImpl.watchFile (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:36:23)
    at ProjectService.openFile (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1361:50)
    at ProjectService.openConfigFile (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1630:33)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/home/corsseir/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1486:41)
[Error - 10:28:17 AM] Notification handler 'textDocument/didOpen' failed with message: watch /home/corsseir/Documents/Projects/translate/frontend/translate/e2e ENOSPC
```

I don't know what is going wrong and why it doesn't work.

**Comment by tarekis** [comment]
I am unsure whether it was really fixed by this, but I have a couple of tools running that need watchers. I see you are working on Linux as well, and probably have not enough inotify watchers. I set it above 100.000 this time, and after a restart of VSCode it seems to work. You could try to use the commands shown here: https://github.com/atom/atom/blob/master/docs/build-instructions/linux.md#typeerror-unable-to-watch-path.

**Comment by Corsseir** [comment]
That did the trick.

**Comment by matheo** [comment]
For the record:
You have to increase number of watched files by inotify.
For testing if this is the reason for this error you can execute:
```
sudo sysctl fs.inotify.max_user_watches=32768
```
then restart VSCode. If now works fine, you can make this setting permanent:
```
echo 32768 | sudo tee -a /proc/sys/fs/inotify/max_user_watches
```
