### ISSUE TITLE
Editing a component will sometimes report a spurious error or throw and exception.

### ISSUE THREAD

**Issue by chuckjaz** [angular/vscode-ng-language-service#18]
```
Users/chuckj/extension/ng-template/client/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27491
	            throw new Error("No Directive annotation found on " + stringify$1(type));
	            ^

Error: No Directive annotation found on AppComponent
    at DirectiveResolver.resolve (/Users/chuckj/extension/ng-template/client/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27491:20)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (/Users/chuckj/extension/ng-template/client/server/node_modules/@angular/language-service/bundles/language-service.umd.js:31502:65)
    at TypeScriptServiceHost.ensureTemplateMap (/Users/chuckj/extension/ng-template/client/server/node_modules/@angular/language-service/bundles/language-service.umd.js:44474:45)
    at TypeScriptServiceHost.getTemplates (/Users/chuckj/extension/ng-template/client/server/node_modules/@angular/language-service/bundles/language-service.umd.js:44373:15)
    at LanguageServiceImpl.getDiagnostics (/Users/chuckj/extension/ng-template/client/server/node_modules/@angular/language-service/bundles/language-service.umd.js:42305:36)
    at /Users/chuckj/extension/ng-template/client/server/editorServices.js:2700:72
    at time (/Users/chuckj/extension/ng-template/client/server/editorServices.js:2691:22)
    at Object.getDiagnostics (/Users/chuckj/extension/ng-template/client/server/editorServices.js:2700:20)
    at ErrorCollector.sendErrorsFor (/Users/chuckj/extension/ng-template/client/server/errors.js:35:39)
    at Timeout.process [as _onTimeout] (/Users/chuckj/extension/ng-template/client/server/errors.js:26:19)
```

**Comment by littleStudent** [comment]
having the exact same issue. Any thoughts on this?

**Comment by chuckjaz** [comment]
I have a fix for this in `@angular/langauge-service`. I will update this plugin with a more up-to-date module this week.

**Comment by marshall007** [comment]
@chuckjaz friendly ping for another release. I haven't been able to get the extension working on a newly generated `4.0.0-rc.2` project (using `@angular/cli v1.0.0-rc.1`). I get this error for inline templates and see nothing at all in external templates.

It would also be great if we could get some documentation on how to build and side-load the extension locally when you get a chance.

**Comment by chuckjaz** [comment]
I am caretaker for Angular this week and will not have time to work on this.

Some things to try:
`npm install --save-dev @angular/language-service@4.0.0-rc.2`
This will be loaded by the plug-in instead of the version it has built in.

If that doesn't help, disable the plugin and install `typescript@next` somewhere outside the project (as we don't support using it yet to compile Angular) and point you typescript language service to that language service an then add:

```
"plugins": [
   { "name": "@angular/language-service" }
 ]
```
to you `"compilerOptions"` section of your `tsconfig.json`. Since `typescript@2.1` will complain about this you need to use a different `tsconfig.json` for building (such as `tsconfig-build.json`).
This will give completions for string literal templates but not external html files.

**Comment by marshall007** [comment]
@chuckjaz to clarify, are you saying I should attempt to install `@angular/language-service` in the project directory? I tried that and it seemed to have no effect. Were you trying to say I should do that somewhere in `~/.vscode/extensions/Google.ng-template-0.0.12`?

**Comment by chuckjaz** [comment]
I was saying install it into the project directory.

The `typescript@next` is the approach I will be converting this plugin to use. Once I convert, this plugin will only be needed to enable completion for external templates.

**Comment by chuckjaz** [comment]
Please re-open if you can still reproduce this in `0.1.0`
