### ISSUE TITLE
Error for getTemplateRefrences

### ISSUE THREAD

**Issue by BartNetJS** [angular/vscode-ng-language-service#182]
I have the error below.
I suppose there is an issue in the tsconfig.json file

```json
{
  "compileOnSave": false,
  "compilerOptions": {
    "outDir": "./dist/out-tsc",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": false,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

Any idea?
Or how i can debug this extension?

this is the error (path replaced with ...)
Search path: ...
Config file name: ...tsconfig.json
Angular Language Service: 5.0.0-beta.5
TypeScript: 2.4.2

Error for getTemplateRefrences:
    RangeError: Maximum call stack size exceeded
    at Map.get (native)
    at StaticReflector.annotations (C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:16917:48)
    at NgModuleResolver.resolve (C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:11218:53)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8808:43)
    at CompileMetadataResolver.getNgModuleSummary (C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8773:35)
    at C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8856:51
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8851:49)
    at CompileMetadataResolver.getNgModuleSummary (C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8773:35)
    at C:\Users\Bart\.vscode\extensions\Angular.ng-template-0.1.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:8856:51

**Comment by trumbitta** [comment]
See #188

**Comment by chuckjaz** [comment]
Can you create a project that duplicates this and supply a link to a repository I can clone?

**Comment by kyliau** [comment]
Issue is two years old and has since been fixed.
