### ISSUE TITLE
Error: Language service does not have a program!

### ISSUE THREAD

**Issue by SIT-jekleine** [angular/vscode-ng-language-service#1827]
# 🐞 bug report

### Description

Language service seems to randomly crash. Restarts resolves the problem and the language service works as expected until a moment when the 'program can't be found'.

## Bug Type
What does this bug affect

- [x ] Angular Language Service VSCode extension
- [x ] Angular Language Service server

## Reproduction

Issue seems to be kinda random. Trying to get some reproduction steps. 

**Expected behavior**

No random crash when getting the 'program'

### **Logs**

<pre><code>
Error: Language service does not have a program!
    at Object.getProgram (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\node_modules\@angular\language-service\bundles\language-service.js:48250:27)
    at CompilerFactory.getOrCreate (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\node_modules\@angular\language-service\bundles\language-service.js:45364:50)
    at LanguageService.withCompilerAndPerfTracing (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\node_modules\@angular\language-service\bundles\language-service.js:48165:51)
    at LanguageService.getSemanticDiagnostics (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\node_modules\@angular\language-service\bundles\language-service.js:47872:25)
    at Object.getSemanticDiagnostics (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\node_modules\@angular\language-service\bundles\language-service.js:48350:38)
    at Session.<anonymous> (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\server\index.js:153733:56)
    at Generator.next (<anonymous>)
    at c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\server\index.js:373:61
    at new Promise (<anonymous>)
    at __async (c:\Users\jeffrey\.vscode\extensions\angular.ng-template-15.0.1\server\index.js:357:10)

</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>Angular CLI: 15.0.0
Node: 18.12.1
Package Manager: npm 7.24.2
OS: win32 x64

Angular: 15.0.0
... animations, cli, common, compiler, compiler-cli, core
... elements, forms, localize, platform-browser
... platform-browser-dynamic, router

Package                         Version
---------------------------------------------------------
@angular-devkit/architect       0.1500.0
@angular-devkit/build-angular   15.0.0
@angular-devkit/core            15.0.0
@angular-devkit/schematics      14.2.10
@angular/cdk                    14.2.2
@schematics/angular             14.2.10
rxjs                            7.5.5
typescript                      4.8.4

</code></pre>

Extension Version:
<pre><code>
v15.0.1
</code></pre>

VSCode Version:
<pre><code>
Version: 1.73.1 (system setup)
Commit: 6261075646f055b99068d3688932416f2346dd3b
Date: (3 wks ago)
Electron: 19.0.17
Chromium: 102.0.5005.167
Node.js: 16.14.2
V8: 10.2.154.15-electron.0
OS Windows NTx6410.022621
Sandboxed: No

</code></pre>

Operating System:
<pre><code>
Edition	Windows 11 Pro
Version	22H2
Installed on	‎29-‎11-‎2022
OS build	22621.819
Experience	Windows Feature Experience Pack 1000.22636.1000.0
</code></pre>

Extension options:
<pre><code>
Default?

</code></pre>

**Anything else relevant?**

**Comment by atscott** [comment]
Generally these types of problems happen when the TypeScript version in your project or the one set in the VSCode extension options for tsdk is not compatible. Are you jumping around projects with different TS versions or does your workspace contain multiple different projects using different TS versions? Did you happen to update the TS version while VSCode was open? Without more information about your workspace or steps to reproduce, this is unfortunately not actionable at the moment.
