### ISSUE TITLE
Error: Cannot resolve type entity i19.IconModule to symbol

### ISSUE THREAD

**Issue by omarAjmi** [angular/vscode-ng-language-service#1852]
## Angular language service exits unexpectedly.
while developing an angular 13 application using this extension v15.1.0 or v13.3.4

## Log
```[Info  - 10:03:10] Using @angular/language-service v13.3.8 from c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\index.js
[Info  - 10:03:10] Logging is turned off. To enable, run command 'Open Angular server log'.
[Info  - 10:03:17] Enabling Ivy language service for e:/projects/anguler/unisoft-ds/tsconfig.json.
c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:23121
            throw new Error(`Cannot resolve type entity ${type.getText()} to symbol`);
                  ^

Error: Cannot resolve type entity i19.IconModule to symbol
    at reflectTypeEntityToDeclaration (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:23121:19)
    at c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:23423:36
    at Array.map (<anonymous>)
    at extractReferencesFromType (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:23418:29)
    at DtsMetadataReader.getNgModuleMetadata (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:23649:26)
    at MetadataDtsModuleScopeResolver.resolve (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:33277:45)
    at LocalModuleScopeRegistry.getExportedScope (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:33763:51)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:33593:42)
    at LocalModuleScopeRegistry.getScopeOfModule (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:33487:22)
    at LocalModuleScopeRegistry.getScopeForComponent (c:\Users\s0100937\.vscode\extensions\angular.ng-template-13.3.4\node_modules\@angular\language-service\bundles\language-service.js:33461:22)
[Error - 10:03:17] Connection to server got closed. Server will not be restarted.```

**Comment by atscott** [comment]
Thanks for reporting this issue. However, you didn't provide sufficient information for us to understand and reproduce the problem. Please check out [our submission guidelines](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-submitting-an-issue) to understand why we can't act on issues that are lacking important information.

If the problem still exists in your application, please [open a new issue](https://github.com/angular/vscode-ng-language-service/issues/new/choose) and follow the instructions in the issue template.
