### ISSUE TITLE
Angular Language Service v15.1.0 crashes on 5 times and is not restarted

### ISSUE THREAD

**Issue by Frazer** [angular/vscode-ng-language-service#1855]
# 🐞 bug report

### Is this a regression?

 Yes, the previous version in which this bug was not present was: ....

v15.0.4

### Description

 A clear and concise description of the problem...
Everyone on my team who is on an intel mac found that  `Angular Language Service server crashed 5 times and is not restarted` each time they open vscode.

Reverting to v15.0.4 fixes this.
Our team on M1 macs did not report this issue. 

## Bug Type

- [ x ] Angular Language Service VSCode extension
- [ x ] Angular Language Service server

as the server is crashed, the extensions function to navigate from templates to matching methods doesn't work.
I am unsure if the extension has any other features.

## Reproduction

Open VSCode on an intel mac, with Angular Language Service v15.1.0

**Expected behavior**

The angular server doesn't crash.

### **Logs**

<pre><code>
Info 0    [17:2:29.2] Format host information updated
Info 1    [17:2:29.2] reload projects.
Info 2    [17:2:29.3] Before ensureProjectForOpenFiles:
Info 3    [17:2:29.3] Open files: 
Info 3    [17:2:29.3] After ensureProjectForOpenFiles:
Info 4    [17:2:29.3] Open files: 
Info 4    [17:2:29.3] Host file extension mappings updated
Info 5    [17:2:29.3] Host watch options changed to {"watchFile":4,"watchDirectory":0,"fallbackPolling":2}, it will be take effect for next watches.
Info 6    [17:2:29.4] Angular language server process ID: 93241
Info 7    [17:2:29.4] Using typescript/lib/tsserverlibrary v4.6.4 from .../node_modules/typescript/lib/tsserverlibrary.js
Info 8    [17:2:29.4] Using @angular/language-service v15.1.0 from ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js
Info 9    [17:2:29.4] Log file: ~/Library/Application Support/Code/logs/20230125T140056/window3/exthost/Angular.ng-template/nglangsvc.log
Info 10   [17:2:29.11] Search path: .../my.component
Info 11   [17:2:29.12] For info: .../my.component.html :: Config file name: .../tsconfig.json
Info 12   [17:2:29.12] Creating configuration project .../tsconfig.json
Info 13   [17:2:29.14] FileWatcher:: Added:: WatchInfo: .../tsconfig.json 2000 {"watchFile":4,"watchDirectory":0,"fallbackPolling":2} Project: .../tsconfig.json WatchType: Config file
Info 14   [17:2:29.15] Loading new project: Creating possible configured project for .../my.component.html to open
Info 15   [17:2:29.344] Config: .../tsconfig.json : {
 "rootNames": [
  ".../dist/browser/assets/i18n/en.ts",
  ".../e2e/app.e2e-spec.ts",
  ".../e2e/app.po.ts",
  ".../807.of.my.ts"
 ],
 "options": {
  "baseUrl": "...",
  "outDir": ".../dist/out-tsc",
  "sourceMap": true,
  "declaration": false,
  "downlevelIteration": true,
  "experimentalDecorators": true,
  "module": 6,
  "moduleResolution": 2,
  "importHelpers": true,
  "target": 7,
  "typeRoots": [
   ".../node_modules/@types"
  ],
  "lib": [
   "lib.es2018.d.ts",
   "lib.dom.d.ts"
  ],
  "plugins": [
   {
    "name": "typescript-strict-plugin"
   }
  ],
  "configFilePath": ".../tsconfig.json"
 }
}
Info 16   [17:2:29.345] DirectoryWatcher:: Added:: WatchInfo: ... 1 {"watchFile":4,"watchDirectory":0,"fallbackPolling":2} Config: .../tsconfig.json WatchType: Wild card directory
Info 17   [17:2:29.345] Elapsed:: 0.5390470027923584ms DirectoryWatcher:: Added:: WatchInfo: ... 1 {"watchFile":4,"watchDirectory":0,"fallbackPolling":2} Config: .../tsconfig.json WatchType: Wild card directory
Info 18   [17:2:29.345] Enabling plugin typescript-strict-plugin from candidate paths: .../node_modules/typescript/lib/tsserverlibrary.js/../../..,~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js
Info 19   [17:2:29.346] Loading typescript-strict-plugin from .../node_modules/typescript/lib/tsserverlibrary.js/../../.. (resolved to .../node_modules/node_modules)
Info 20   [17:2:29.367] Loading typescript-strict-plugin from ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js (resolved to ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js/node_modules)
Info 21   [17:2:29.367] Failed to load module 'typescript-strict-plugin' from .../node_modules/node_modules: Error: Angular server will not load plugin 'typescript-strict-plugin'.
    at ServerHost.require (~/.vscode/extensions/angular.ng-template-15.1.0/server/index.js:724:20)
    at Project.resolveModule (.../node_modules/typescript/lib/tsserverlibrary.js:166368:35)
    at .../node_modules/typescript/lib/tsserverlibrary.js:167464:36
    at Object.firstDefined (.../node_modules/typescript/lib/tsserverlibrary.js:407:26)
    at Project.enablePlugin (.../node_modules/typescript/lib/tsserverlibrary.js:167463:41)
    at ConfiguredProject.enablePluginsWithOptions (.../node_modules/typescript/lib/tsserverlibrary.js:168074:30)
    at ProjectService.loadConfiguredProject (.../node_modules/typescript/lib/tsserverlibrary.js:169784:25)
    at ProjectService.createAndLoadConfiguredProject (.../node_modules/typescript/lib/tsserverlibrary.js:169737:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (.../node_modules/typescript/lib/tsserverlibrary.js:169742:36)
    at ProjectService.assignProjectToOpenedScriptInfo (.../node_modules/typescript/lib/tsserverlibrary.js:170826:44)
Info 22   [17:2:29.367] Failed to load module 'typescript-strict-plugin' from ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js/node_modules: Error: Angular server will not load plugin 'typescript-strict-plugin'.
    at ServerHost.require (~/.vscode/extensions/angular.ng-template-15.1.0/server/index.js:724:20)
    at Project.resolveModule (.../node_modules/typescript/lib/tsserverlibrary.js:166368:35)
    at .../node_modules/typescript/lib/tsserverlibrary.js:167464:36
    at Object.firstDefined (.../node_modules/typescript/lib/tsserverlibrary.js:407:26)
    at Project.enablePlugin (.../node_modules/typescript/lib/tsserverlibrary.js:167463:41)
    at ConfiguredProject.enablePluginsWithOptions (.../node_modules/typescript/lib/tsserverlibrary.js:168074:30)
    at ProjectService.loadConfiguredProject (.../node_modules/typescript/lib/tsserverlibrary.js:169784:25)
    at ProjectService.createAndLoadConfiguredProject (.../node_modules/typescript/lib/tsserverlibrary.js:169737:22)
    at ProjectService.createLoadAndUpdateConfiguredProject (.../node_modules/typescript/lib/tsserverlibrary.js:169742:36)
    at ProjectService.assignProjectToOpenedScriptInfo (.../node_modules/typescript/lib/tsserverlibrary.js:170826:44)
Info 23   [17:2:29.367] Couldn't find typescript-strict-plugin
Info 24   [17:2:29.367] Loading global plugin @angular/language-service
Info 25   [17:2:29.367] Enabling plugin @angular/language-service from candidate paths: ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js,.../node_modules/typescript/lib/tsserverlibrary.js/../../..
Info 26   [17:2:29.367] Loading @angular/language-service from ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js (resolved to ~/.vscode/extensions/angular.ng-template-15.1.0/node_modules/@angular/language-service/index.js/node_modules)
Info 27   [17:2:29.627] Angular compiler options for .../tsconfig.json: {
  "baseUrl": "...",
  "outDir": ".../dist/out-tsc",
  "sourceMap": true,
  "declaration": false,
  "downlevelIteration": true,
  "experimentalDecorators": true,
  "module": 6,
  "moduleResolution": 2,
  "importHelpers": true,
  "target": 7,
  "typeRoots": [
    ".../node_modules/@types"
  ],
  "lib": [
    "lib.es2018.d.ts",
    "lib.dom.d.ts"
  ],
  "plugins": [
    {
      "name": "typescript-strict-plugin"
    }
  ],
  "configFilePath": ".../tsconfig.json",
  "genDir": "...",
  "basePath": "...",
  "fullTemplateTypeCheck": true,
  "strictInjectionParameters": true,
  "compileNonExportedClasses": false
}
Info 28   [17:2:29.628] Plugin validation succeeded

Info 35   [17:2:29.630] FileWatcher:: Added:: WatchInfo: .../806.of.my.ts 500 {"watchFile":4,"watchDirectory":0,"fallbackPolling":2} WatchType: Closed Script info

Lots of imports et al.

</code></pre>

## 🌍  Your Environment
**Angular Version:**
<pre><code>
Angular: 14.1.3
</code></pre>

Extension Version:
<pre><code>
v15.1.0
</code></pre>

VSCode Version:
<pre><code>
1.74.3
</code></pre>

Operating System:
<pre><code>
mac v12.6.2
</code></pre>

Extension options:
<pre><code>
"angular.experimental-ivy": true,
</code></pre>

**Anything else relevant?**
fixed by reverting to angular language server 15.0.4

**Comment by atscott** [comment]
It looks like v15.1 is using [typescript version 4.9](https://github.com/angular/angular/blob/99723fc64ed6ded3635ae5e19648550dc42f1bc1/package.json#L173). From the logs, it looks like the project is on v4.6.4. 

Even in v15.0.4 of the extension, the [minimum required version of TypeScript is 4.8](https://github.com/angular/vscode-ng-language-service/blob/15.0.x/server/src/version_provider.ts#L15) so I'm a bit surprised the logs indicate 4.6 was selected from the node_modules folder rather than the version bundled in the extension (the line would have looked like this instead in that case: `Info 7    [15:47:17.344] Using typescript/lib/tsserverlibrary v4.8.2 from /Users/atscott/.vscode/extensions/angular.ng-template-15.1.0/node_modules/typescript/lib/tsserverlibrary.js`

A couple things to try:
* Just to eliminate any weird problems: Has VSCode been restarted since installing the new extension version?
* I realize the project might not be ready to update typescript, but if you update to 4.8 or 4.9, does that resolve the crash? If so, then the problem is likely an incompatibility between the TS versions required by the compiler in v15.1 and the project's version.

**Comment by atscott** [comment]
I've also tried adding the plugin "typescript-strict-plugin" and indeed it fails to load the plugin but it does not result in a crash. Is there any additional information in the server logs about the crash or in the output tab? At the moment, there's not enough information here to reproduce the issue and the included logs don't show the failure. An example project would be helpful as well. 

![image](https://user-images.githubusercontent.com/479713/217039813-db356ac9-830b-44ce-abff-1cbdeaba08c4.png)

**Comment by bageren** [comment]
Happens to me too on 15.1.0. I'm also on an Intel Mac.

On any other 15.x version, ngFor loops aren't working for me. It correctly determines the types of the arrays but thinks all elements inside are 'unknown'.

At least 14.2.0 seems to be working. I guess I'll have to stick with that for now.

**Comment by atscott** [comment]
@bageren Do you have any additional information about the crash? This would appear in the output tab as pictured in my previous comment.

**Comment by dylhunn** [comment]
Here's a theory of the problem.

Your startup logs show you are using TS 4.6, which is too low a version to be supported with Angular 15.1. This is supposed to be impossible -- we enforce a MIN_VERSION check of TS > 4.8. I'm not sure why it's only happening on Intel, but it could be that only your Intel users are overriding the TS version to be too low.

In your VSCode settings for the Angular Language Service Extension, are these users setting the `tsdk` version explicitly?

I'd also be curious to know if your M1 users have logs showing a more up to date TS version (4.8 or 4.9).

**Comment by dylhunn** [comment]
To mitigate this issue in the future, @atscott and I are also updating the language service to show more explicit warnings when misconfigured with an out-of-date typescript version, including via the `tsdk` option.

**Comment by dylhunn** [comment]
We are committing a fix to cause the TSDK setting to be ignored if it's too old. Let us know if this isn't the root cause.

**Comment by ChrisRogers-TheNBS** [comment]
I've experienced this issue as well, although I was explicitly setting `Tsdk` in my workspace settings to the version of the project, which is v4.6. Clearing the `Tsdk` value back to default seems to have resolved the issue and it no longer crashes for me.

**Comment by Frazer** [comment]
How do I answer `In your VSCode settings for the Angular Language Service Extension, are these users setting the tsdk version explicitly?`

We also updated to TS 4.9 ( we have a workspace setting that was choosing v4.9, and we clicked on {} in the bottom bar, and chose 4.9 and restarted ), but the angular service still crashes.

In the log, we still see:
Using typescript/lib/tsserverlibrary v4.6.4 from …/node_modules/typescript/lib/tsserverlibrary.js

**Comment by Frazer** [comment]
Oh, I found why.

We have this in workspace settings.json

{
  "typescript.enablePromptUseWorkspaceTsdk": true,
  "typescript.tsdk": "client/node_modules/typescript/lib"
}

**Comment by BenRacicot** [comment]
@Frazer are you sure that was the cause? I'm suddenly seeing the same error only on one project. Been at this for hours now.

Where did you check that TS log BTW?

**Comment by BenRacicot** [comment]
Very helpful thank you! Angular language server is in fact crashing.

```
[Info  - 2:51:24 PM] Angular language server process ID: 7214
[Info  - 2:51:24 PM] Using typescript/lib/tsserverlibrary v4.9.5 from /Users/bracicot/dev/recruitler-client/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 2:51:24 PM] Using @angular/language-service v15.2.0-next.1 from /Users/bracicot/.vscode/extensions/angular.ng-template-15.2.0-next.0/node_modules/@angular/language-service/index.js
[Info  - 2:51:24 PM] Log file: /Users/bracicot/Library/Application Support/Code/logs/20230222T145122/window1/exthost/Angular.ng-template/nglangsvc.log
[Error - 2:51:25 PM] No config file for ...rankings-results/rankings-results.component.html
[Error - 2:51:25 PM] No config file for ...rankings-results/rankings-results.component.html
[Error - 2:51:44 PM] No config file for ...rankings-results/rankings-results.component.html
[Info  - 2:51:49 PM] Enabling Ivy language service for /Users/bracicot/dev/recruitler-client/tsconfig.json.
/Users/bracicot/dev/recruitler-client/node_modules/typescript/lib/tsserverlibrary.js:19074
    function hasSyntacticModifier(node, flags) {
                                 ^

RangeError: Maximum call stack size exceeded
    ...
        _reflectMember(node) {
```

Above are the first 2 errors. There are a total of 5 errors until it does not try to restart.
It also seems like I have no intellisense either but all TS/Intellisense settings are as expected.

**Comment by atscott** [comment]
@BenRacicot Ah, that's interesting. Can you open a new issue for this? It's definitely a different problem than what's been reported here. We'd also need a reproduction -- you can try to get one by progressively removing chunks of your application until you find what component is causing it. Seems like there's something causing an infinite loop.

**Comment by BenRacicot** [comment]
I found it (albeit without intellisense) 
A component was included within two modules. 

I'm bringing a bunch of code form an older app into a new one. Now that I know what it is I recognized that as soon as intellisense processes that feature's files it never recovered. I removed that entire feature and intellisense/NGLS no longer crashes.

**Comment by atscott** [comment]
Hmm, that doesn't seem like it should cause the crash on its own. Are you able to provide a reproduction? Adding a component to two modules in our test project does not result in a crash but does produce the correct diagnostic:
https://github.com/angular/vscode-ng-language-service/commit/761c20e2fd0b46238897791d0353a799b627e374
<img width="1029" alt="image" src="https://user-images.githubusercontent.com/479713/220786371-d96dc2d2-9ebb-4e07-b6bd-433877020427.png">

**Comment by BenRacicot** [comment]
> Hmm, that doesn't seem like it should cause the crash on its own. Are you able to provide a reproduction? Adding a component to two modules in our test project does not result in a crash but does produce the correct diagnostic: [761c20e](https://github.com/angular/vscode-ng-language-service/commit/761c20e2fd0b46238897791d0353a799b627e374) <img alt="image" width="1029" src="https://user-images.githubusercontent.com/479713/220786371-d96dc2d2-9ebb-4e07-b6bd-433877020427.png">

Hey sorry, I'm trying to get back to this to create a replication for you and the community. But I can assure you that it was my own code. The module issues. Removing my `jobs` feature entirely (the one where the `job` component was included within 2 modules) stopped the issue from happening.
