### ISSUE TITLE
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined

### ISSUE THREAD

**Issue by ghost** [angular/vscode-ng-language-service#191]
I've created a project with @angular/cli@1.5.0.

There are errors in output when I edit *.component.html files:

```
[Error - 21:35:05] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'lineNumberToInfo' of undefined
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:659:29)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:30)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:152:56
    at TextDocuments.logErrors (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:149:76
    at handleNotification (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
    at process.callback (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:489:13)
    at emitTwo (events.js:106:13)
[Error - 21:35:05] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'lineNumberToInfo' of undefined
[Error - 21:35:05] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'lineNumberToInfo' of undefined
  Code: -32603 
[Error - 21:35:05] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'lineNumberToInfo' of undefined
  Code: -32603 
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:659:29)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:30)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:152:56
    at TextDocuments.logErrors (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:149:76
    at handleNotification (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
    at process.callback (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:489:13)
    at emitTwo (events.js:106:13)
[Error - 21:35:05] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'lineNumberToInfo' of undefined
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:659:29)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:30)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:152:56
    at TextDocuments.logErrors (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:149:76
    at handleNotification (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
    at process.callback (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:489:13)
    at emitTwo (events.js:106:13)
[Error - 21:35:05] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'lineNumberToInfo' of undefined
[Error - 21:35:05] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'lineNumberToInfo' of undefined
  Code: -32603 
[Error - 21:35:05] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'lineNumberToInfo' of undefined
  Code: -32603 
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:659:29)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:30)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:152:56
    at TextDocuments.logErrors (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:149:76
    at handleNotification (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
    at process.callback (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:489:13)
    at emitTwo (events.js:106:13)
[Error - 21:35:05] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'lineNumberToInfo' of undefined
SERVER ERROR: Cannot read property 'lineNumberToInfo' of undefined
TypeError: Cannot read property 'lineNumberToInfo' of undefined
    at LSHost.lineOffsetToPosition (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:659:29)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:86
    at Array.map (native)
    at ProjectService.lineOffsetsToPositions (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1448:30)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:152:56
    at TextDocuments.logErrors (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:235:13)
    at /Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/documents.js:149:76
    at handleNotification (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:353:21)
    at process.callback (/Users/serge/.vscode/extensions/Angular.ng-template-0.1.7/server/node_modules/vscode-jsonrpc/lib/main.js:489:13)
    at emitTwo (events.js:106:13)
[Error - 21:35:05] Notification handler 'textDocument/didChange' failed with message: Cannot read property 'lineNumberToInfo' of undefined
[Error - 21:35:05] Request textDocument/completion failed.
```

**Comment by chuckjaz** [comment]
These stack traces are insufficient information for me to diagnose this problem.

Can you describe the steps you took to arrive at these errors? Is is possible to produce a project that always reproduces these?

**Comment by kyliau** [comment]
Issue is two years old and has since been fixed.
