### ISSUE TITLE
Angular language service crash with error "Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by zzg890** [angular/vscode-ng-language-service#1919]
# 🐞 bug report

### Is this a regression?

 No, this error occurs after project files updated.

### Description

 When the angular language server starts, I got the following error. 
[Info  - 10:06:12 AM] Angular language server process ID: 58684
[Info  - 10:06:12 AM] Using typescript/lib/tsserverlibrary v5.1.3 from c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 10:06:12 AM] Using @angular/language-service v16.1.8 from c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\index.js
[Info  - 10:06:12 AM] Log file: c:\Users\ZZhang\AppData\Roaming\Code\logs\20230911T095257\window1\exthost\Angular.ng-template\nglangsvc.log
[Info  - 10:06:19 AM] Enabling Ivy language service for d:/repos/scada-phase5-master/webui/tsconfig.json.
[Error - 10:06:21 AM] RangeError: Maximum call stack size exceeded
    at MetadataDtsModuleScopeResolver.resolve (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28370:16)
    at LocalModuleScopeRegistry.getExportedScope (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28928:51)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28722:42)
    at LocalModuleScopeRegistry.getScopeOfModule (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28620:22)
    at LocalModuleScopeRegistry.getScopeForComponent (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28594:22)
    at makeNotStandaloneDiagnostic (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28476:35)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28753:42)
    at LocalModuleScopeRegistry.getScopeOfModule (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28620:22)
    at LocalModuleScopeRegistry.getScopeForComponent (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28594:22)
    at makeNotStandaloneDiagnostic (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28476:35)
[Error - 10:06:21 AM] Notification handler 'textDocument/didOpen' failed with message: Maximum call stack size exceeded
c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28676
        getScopeOfModuleReference(ref) {
                                 ^

RangeError: Maximum call stack size exceeded
    at LocalModuleScopeRegistry.getScopeOfModuleReference (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28676:34)
    at LocalModuleScopeRegistry.getScopeOfModule (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28620:22)
    at LocalModuleScopeRegistry.getScopeForComponent (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28594:22)
    at makeNotStandaloneDiagnostic (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28476:35)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28753:42)
    at LocalModuleScopeRegistry.getScopeOfModule (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28620:22)
    at LocalModuleScopeRegistry.getScopeForComponent (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28594:22)
    at makeNotStandaloneDiagnostic (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28476:35)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28753:42)
    at LocalModuleScopeRegistry.getScopeOfModule (c:\Users\ZZhang\.vscode\extensions\angular.ng-template-16.1.8\node_modules\@angular\language-service\bundles\language-service.js:28620:22)

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

## Bug Type
What does this bug affect

- [ ] Angular Language Service VSCode extension
- [x] Angular Language Service server

## Reproduction

1. Open an angular project with massive TS files by VSCode.
2. Click the output tab

**Expected behavior**

### **Logs**

Log file gives us deep insight into the behavior and performance of the extension. If the issue is a performance
problem or an error occured, please provide the output of the log file below.

Set Angular Log level to verbose.

<pre><code>

</code></pre>

### **Screenshots**

![Example Screenshot](./output.png)

## 🌍  Your Environment
**Angular Version:
<pre><code>

  14.2.12

</code></pre>

Extension Version: 
<pre><code>

16.1.8

</code></pre>

VSCode Version: 
<pre><code>

1.80.1

</code></pre>

Operating System: 
<pre><code>

Windows 11

</code></pre>

Extension options:
<pre><code>

</code></pre>

**Anything else relevant?**

**Comment by zzg890** [comment]
Not a bug, just project source error.
