### ISSUE TITLE
Error no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by MonsieurMan** [angular/vscode-ng-language-service#193]
I keep getting this error when editing non angular projects. I guess the extension doesn't detect when the loaded project is not using angular, are there any reason for it ?   
```bash
Search path: /home/MrMan/Desktop/Projects/forks/nest-cli/src
Config file name: /home/MrMan/Desktop/Projects/forks/nest-cli/tsconfig.json
SERVER ERROR: ENOENT: no such file or directory, uv_cwd
Error: ENOENT: no such file or directory, uv_cwd
    at Object.readDirectory (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:3853:111)
    at ProjectServiceHostImpl.readDirectory (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/documents.js:39:23)
    at matchFileNames (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:72075:40)
    at getFileNames (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:71795:26)
    at Object.parseJsonConfigFileContent (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/node_modules/typescript/lib/typescript.js:71742:18)
    at ProjectService.configFileToProjectOptions (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1600:36)
    at ProjectService.openConfigFile (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1620:42)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1486:41)
    at ProjectService.openClientFile (/home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/editorServices.js:1404:23)
    at /home/MrMan/.vscode-insiders/extensions/Angular.ng-template-0.1.7/server/documents.js:135:47
[Error - 8:48:32 AM] Notification handler 'textDocument/didOpen' failed with message: ENOENT: no such file or directory, uv_cwd
```

I think I'll track it down later, and so I have one more question, why the hell is the editorServices file over 2000 lines ?

**Comment by MonsieurMan** [comment]
Closing as I never got through investigating it more.
