### ISSUE TITLE
Error: Cannot resolve type entity i3.CommonModule to symbol

### ISSUE THREAD

**Issue by 05jackson** [angular/vscode-ng-language-service#1984]
# 🐞 bug report

### Is this a regression?

No.

### Description

Extension randomly crashes a few times when vscode is started. Usually can be fixed by restarting vscode a few times.

## Bug Type
What does this bug affect

- [X] Angular Language Service VSCode extension
- [ ] Angular Language Service server

## Reproduction

Not sure, happens randomly. If vscode is restarted a few times that usually fixes things

**Expected behavior**

A working extension

### **Logs**

<code>Err 1141  [4:20:40.726] Error: Cannot resolve type entity i3.CommonModule to symbol
    at reflectTypeEntityToDeclaration (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:33734:19)
    at extraReferenceFromTypeQuery (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:38174:32)
    at /Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:38169:20
    at Array.map (<anonymous>)
    at extractReferencesFromType (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:38165:29)
    at DtsMetadataReader.getNgModuleMetadata (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:38412:26)
    at MetadataDtsModuleScopeResolver.resolve (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:41256:45)
    at LocalModuleScopeRegistry.getExportedScope (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:41803:51)
    at LocalModuleScopeRegistry.getScopeOfModuleReference (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:41597:42)
    at LocalModuleScopeRegistry.getExportedScope (/Users/USERNAME/.vscode/extensions/angular.ng-template-17.0.3/node_modules/@angular/language-service/bundles/language-service.js:41807:29)
</code>

## 🌍  Your Environment
**Angular Version:**
16.2.1

Extension Version:
17.0.3

VSCode Version:
latest

Operating System:
MacOs

**Comment by atscott** [comment]
Hi @05jackson, I would love to fix this issue. Unfortunately there’s not enough information to reproduce it and investigate so I’m going to close this as not actionable. Please open a new issue if you’re able to pin down a reproduction.
