### ISSUE TITLE
template fold variable break

### ISSUE THREAD

**Issue by 0-don** [angular/vscode-ng-language-service#2010]
# 🐞 bug report

### Description
This bug is caused by a template variable inside template string section the folding breaks and you cant minimize the elements

## Reproduction
![image](https://github.com/angular/vscode-ng-language-service/assets/70039285/c10788d7-3480-40d9-939f-a326eef70b23)

**Comment by ohadf2015** [comment]
is this related to the following Error that cause the service to crash?
```
Request textDocument/foldingRange failed with message: Maximum call stack size exceeded: Error: Request textDocument/foldingRange failed with message: Maximum call stack size exceeded
    at handleResponse (/Users/ohad/.vscode/extensions/angular.ng-template-17.3.1/node_modules/vscode-jsonrpc/lib/common/connection.js:477:48)
    at processMessageQueue (/Users/ohad/.vscode/extensions/angular.ng-template-17.3.1/node_modules/vscode-jsonrpc/lib/common/connection.js:292:17)
    at Immediate.<anonymous> (/Users/ohad/.vscode/extensions/angular.ng-template-17.3.1/node_modules/vscode-jsonrpc/lib/common/connection.js:276:13)
    at processImmediate (node:internal/timers:476:21)
```
