### ISSUE TITLE
The Language Client for Angular @Component Extension server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by mickeyjohn** [angular/vscode-ng-language-service#204]
Hi,
It is only happening with my NodeJS BackEnd project using VSCode version 1.19.1. One strange thing is It does not with another window openning my Angular project folder.

The detail log (taken from Ouput panel):
/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256
        }).reduce((p, c) => p.concat(c)).filter(x => x);
           ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at glob (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256:12)
    at f (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:197:8)
    at done (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:637:12)
    at /home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:626:10
[Info  - 16:26:09] Connection to server got closed. Server will restart.
/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256
        }).reduce((p, c) => p.concat(c)).filter(x => x);
           ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at glob (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256:12)
    at f (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:197:8)
    at done (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:637:12)
    at /home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:626:10
[Info  - 16:26:09] Connection to server got closed. Server will restart.
/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256
        }).reduce((p, c) => p.concat(c)).filter(x => x);
           ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at glob (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256:12)
    at f (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:197:8)
    at done (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:637:12)
    at /home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:626:10
[Info  - 16:26:09] Connection to server got closed. Server will restart.
/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256
        }).reduce((p, c) => p.concat(c)).filter(x => x);
           ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at glob (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256:12)
    at f (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:197:8)
    at done (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:637:12)
    at /home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:626:10
[Info  - 16:26:10] Connection to server got closed. Server will restart.
/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256
        }).reduce((p, c) => p.concat(c)).filter(x => x);
           ^

TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at glob (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/out/src/server.js:256:12)
    at f (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/once/once.js:25:25)
    at Glob.<anonymous> (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:151:7)
    at emitOne (events.js:96:13)
    at Glob.emit (events.js:191:7)
    at Glob._finish (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:197:8)
    at done (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:182:14)
    at Glob._processGlobStar2 (/home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:637:12)
    at /home/user/.vscode/extensions/onixie.angular-component-extension-0.0.12/node_modules/glob/glob.js:626:10
[Error - 16:26:10] Connection to server got closed. Server will not be restarted.

Will it affect any functions of VSCode or plugins? Please help fix.

Thanks a lot.

**Comment by chuckjaz** [comment]
This error does not appear to be coming from the angular language service.

Please report to the onixie.angular-component-extension-0.0.12.
