### ISSUE TITLE
Server cannot start

### ISSUE THREAD

**Issue by dmaglio** [angular/vscode-ng-language-service#243]
VSCode: 1.23.0
OS: Windows 10 64bit

Output console:
```
[Info  - 14:30:37] Connection to server got closed. Server will restart.
module.js:472
    throw err;
    ^

Error: Cannot find module './events'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\dma02\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\vscode-jsonrpc\lib\messageReader.js:17:16)
    at Object.<anonymous> (C:\Users\dma02\.vscode\extensions\Angular.ng-template-0.1.9\server\node_modules\vscode-jsonrpc\lib\messageReader.js:272:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
```

**Comment by kyliau** [comment]
Closing this, since issue is likely fixed in latest version. Please reopen otherwise.
