### ISSUE TITLE
Rename fails or works incorrectly

### ISSUE THREAD

**Issue by anvlkv** [angular/vscode-ng-language-service#297]
When renaming let's say method in service:

    Search path: c:/Code/Applications/....Web/.../src/app/flow/share-button
    Config file name: c:/Code/Applications/....Web/.../tsconfig.json
    SERVER ERROR: Unexpected token } in JSON at position 494
    SyntaxError: Unexpected token } in JSON at position 494
        at JSON.parse (<anonymous>)
        at parseAndReEmitConfigJSONFile (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\editorServices.js:257:33)
        at ProjectService.configFileToProjectOptions (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\editorServices.js:1598:18)
        at ProjectService.openConfigFile (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\editorServices.js:1620:42)
        at ProjectService.openOrUpdateConfiguredProjectForFile (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\editorServices.js:1486:41)
        at ProjectService.openClientFile (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\editorServices.js:1404:23)
        at c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\documents.js:180:38
        at TextDocuments.logErrors (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\documents.js:235:13)
        at c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\documents.js:173:74
        at handleNotification (c:\Users\Aleksandr....\.vscode\extensions\angular.ng-template-0.1.10\server\node_modules\vscode-jsonrpc\lib\main.js:483:43)
    [Error - 10:12:13 AM] Notification handler 'textDocument/didSave' failed with message: Unexpected token } in JSON at position 494

Yesterday had vscode showing error. Today it renamed the method... in one place out of 50.

**Comment by ananiy** [comment]
+1

**Comment by kyliau** [comment]
The language service does not support renaming (yet).
The error you saw was due to JSON parsing (unrelated to renaming), which was fixed in https://github.com/angular/vscode-ng-language-service/pull/346
