### ISSUE TITLE
Unexpected token at position 474

### ISSUE THREAD

**Issue by Maryannah** [angular/vscode-ng-language-service#314]
Just updated VSCode, but have been having issues for about 1 or 2 upgrades now. 

Decided to open the console today. 

Reloaded the window to be sure. 

Message displayed : 

```
SyntaxError: Unexpected token } in JSON at position 474
    at JSON.parse (<anonymous>)
    at parseAndReEmitConfigJSONFile (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\editorServices.js:260:33)
    at ProjectService.configFileToProjectOptions (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\editorServices.js:1601:18)
    at ProjectService.openConfigFile (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\editorServices.js:1623:42)
    at ProjectService.openOrUpdateConfiguredProjectForFile (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\editorServices.js:1489:41)
    at ProjectService.openClientFile (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\editorServices.js:1407:23)
    at c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\documents.js:135:47
    at TextDocuments.logErrors (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\documents.js:235:13)
    at c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\documents.js:131:74
    at handleNotification (c:\Users\MT4E45CN\.vscode\extensions\angular.ng-template-0.1.11\server\node_modules\vscode-jsonrpc\lib\main.js:489:43)
[Error - 16:26:15] Notification handler 'textDocument/didOpen' failed with message: Unexpected token } in JSON at position 474
```

Relevant informations : 

ALS : 0.1.11
VSCode : 1.31.0
NodeJS: 10.2.0
TDSK : 3.0.0-dev.20180711

Let me know if you need more information about the issue or my setup. 

Thank you in advance.

**Comment by rodmax** [comment]
It seems the bug in angular-language-service package
https://github.com/angular/angular/issues/21729#issue-290921847

Quick fix  is to modify your tsconfig.json files to pure JSON format ( remove all comments and trailing commas in last elements of objects/array)
