### ISSUE TITLE
Extension does not work after updating to Angular v8.1.0

### ISSUE THREAD

**Issue by ramunas-k** [angular/vscode-ng-language-service#343]
I use this extension a lot, but today after updating to Angular v8.1.0 I noticed that I'm not getting any support from it. Here is the extension output:
```
Search path: /home/user/git/project/src/app/campaigns/campaign-list
Config file name: /home/user/git/project/tsconfig.json
Angular Language Service: 8.1.0
TypeScript: 3.4.5
SERVER ERROR: this.ngHost.setSite is not a function
TypeError: this.ngHost.setSite is not a function
    at new CompilerService (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1754:21)
    at new Project (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:705:36)
    at ProjectService.createProject (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1726:23)
    at ProjectService.openConfigFile (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1629:28)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1489:41)
    at ProjectService.openClientFile (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1407:23)
    at /home/user/.vscode/extensions/angular.ng-template-0.800.0/server/documents.js:135:47
    at TextDocuments.logErrors (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/documents.js:235:13)
    at /home/user/.vscode/extensions/angular.ng-template-0.800.0/server/documents.js:131:74
    at handleNotification (/home/user/.vscode/extensions/angular.ng-template-0.800.0/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
[Error - 10:41:05 AM] Notification handler 'textDocument/didOpen' failed with message: this.ngHost.setSite is not a function
```
`ng version` output:
```
Angular CLI: 8.1.0
Node: 12.6.0
OS: linux x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.801.0
@angular-devkit/build-angular     0.801.0
@angular-devkit/build-optimizer   0.801.0
@angular-devkit/build-webpack     0.801.0
@angular-devkit/core              8.1.0
@angular-devkit/schematics        8.1.0
@ngtools/webpack                  8.1.0
@schematics/angular               8.1.0
@schematics/update                0.801.0
rxjs                              6.5.2
typescript                        3.4.5
webpack                           4.35.2
```
Downgrading Angular back to v8.0.3 fixes the issue.

P.S. I have originally filed this issue as related to updating to VSCode 1.36, but it has nothing to do with it. VSCode 1.36 + Angular v8.0.3 this extensions works like a charm

**Comment by marcopetreri** [comment]
Same problem, here is my outputs.

Angular Language Service
```Search path: /Users/marcopetreri/projects/***/projects/configuration/src/lib/services
Config file name: /Users/marcopetreri/projects/***/tsconfig.json
Angular Language Service: 8.1.0
TypeScript: 3.4.5
SERVER ERROR: this.ngHost.setSite is not a function
TypeError: this.ngHost.setSite is not a function
    at new CompilerService (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1754:21)
    at new Project (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:705:36)
    at ProjectService.createProject (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1726:23)
    at ProjectService.openConfigFile (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1629:28)
    at ProjectService.openOrUpdateConfiguredProjectForFile (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1489:41)
    at ProjectService.openClientFile (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/editorServices.js:1407:23)
    at /Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/documents.js:180:38
    at TextDocuments.logErrors (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/documents.js:235:13)
    at /Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/documents.js:173:74
    at handleNotification (/Users/marcopetreri/.vscode/extensions/angular.ng-template-0.800.0/server/node_modules/vscode-jsonrpc/lib/main.js:489:43)
[Error - 2:37:03 PM] Notification handler 'textDocument/didSave' failed with message: this.ngHost.setSite is not a function
```

Angular CLI version output
```Angular CLI: 8.1.0
Node: 12.6.0
OS: darwin x64
Angular: 8.1.0
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.801.0
@angular-devkit/build-angular      0.801.0
@angular-devkit/build-ng-packagr   0.801.0
@angular-devkit/build-optimizer    0.801.0
@angular-devkit/build-webpack      0.801.0
@angular-devkit/core               8.1.0
@angular-devkit/schematics         8.1.0
@ngtools/json-schema               1.1.0
@ngtools/webpack                   8.1.0
@schematics/angular                8.1.0
@schematics/update                 0.801.0
ng-packagr                         5.3.0
rxjs                               6.4.0
typescript                         3.4.5
webpack                            4.35.2
```

**Comment by justerest** [comment]
**Temporary solution**

You can downgrade local version of `@angular/language-service` to `8.0.3`.

<img width="898" alt="Снимок экрана 2019-07-05 в 12 20 07" src="https://user-images.githubusercontent.com/24754883/60704934-3dbb5300-9f1f-11e9-866c-598af1035529.png">

**Comment by sanket-bhalerao** [comment]
Is the fix going to be released any time soon?

**Comment by lucas-labs** [comment]
Same problem here. The extension isn't working at all. Here's my output:

```
Search path: c:/Users/lucas/***/src/app/components/app
Config file name: c:/Users/lucas/***/tsconfig.json
Angular Language Service: 8.1.0
TypeScript: 3.4.5
SERVER ERROR: this.ngHost.setSite is not a function
TypeError: this.ngHost.setSite is not a function
    at new CompilerService (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\editorServices.js:1754:21)
    at new Project (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\editorServices.js:705:36)
    at ProjectService.createProject (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\editorServices.js:1726:23)
    at ProjectService.openConfigFile (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\editorServices.js:1629:28)
    at ProjectService.openOrUpdateConfiguredProjectForFile (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\editorServices.js:1489:41)
    at ProjectService.openClientFile (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\editorServices.js:1407:23)
    at c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\documents.js:135:47
    at TextDocuments.logErrors (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\documents.js:235:13)
    at c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\documents.js:131:74
    at handleNotification (c:\Users\lucas\.vscode\extensions\angular.ng-template-0.800.0\server\node_modules\vscode-jsonrpc\lib\main.js:489:43)
```

**Comment by david0178418** [comment]
Save as everyone above.

**Comment by BlindDespair** [comment]
Having same issue here.

**Comment by mucbits** [comment]
Problem still exists in version 8.1.1
```
Angular Language Service: 8.1.1
TypeScript: 3.4.5
SERVER ERROR: this.ngHost.setSite is not a function
TypeError: this.ngHost.setSite is not a function
```

**Comment by donsumayan** [comment]
Same issue as everyone

**Comment by baratgabor** [comment]
Same issue here as well, with 8.1.1.

**Comment by kyliau** [comment]
Thank you @andrius-pra for fixing this. I apologize for the regression, it was totally my oversight for failing to take into account the breaking change here. Version 0.801.1 has been released on the marketplace.
