### ISSUE TITLE
Extension stopped working

### ISSUE THREAD

**Issue by Dunsteer** [angular/vscode-ng-language-service#353]
The extension has been working perfectly for a few months and then out of thin air nothing, completely stopped. Tried reinstalling it but that hasn't fixed anything. I haven't upgraded my project to 8.1.0, at least that's what `ng version` says. Any ideas? I don't know what happed...

**Comment by andrius-pra** [comment]
Do you have any errors in console panel of Angular Language language service?

**Comment by Dunsteer** [comment]
```
SERVER ERROR: Unexpected token } in JSON at position 953
SyntaxError: Unexpected token } in JSON at position 953
at JSON.parse (<anonymous>)
    at parseAndReEmitConfigJSONFile (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\editorServices.js:260:33)
    at ProjectService.configFileToProjectOptions (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\editorServices.js:1601:18)
    at ProjectService.openConfigFile (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\editorServices.js:1623:42)
    at ProjectService.openOrUpdateConfiguredProjectForFile (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\editorServices.js:1489:41)
    at ProjectService.openClientFile (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\editorServices.js:1407:23)
    at c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\documents.js:135:47
    at TextDocuments.logErrors (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\documents.js:235:13)
    at c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\documents.js:131:74
    at handleNotification (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\node_modules\vscode-jsonrpc\lib\main.js:489:43)
[Error - 8:08:54 PM] Notification handler 'textDocument/didOpen' failed with message: Unexpected token } in JSON at position 953
```
This is the error I get.

**Comment by andrius-pra** [comment]
Quick fix is [here](https://github.com/angular/vscode-ng-language-service/issues/314#issuecomment-479779944). It will be fixed by #346 in next version.

**Comment by Dunsteer** [comment]
After fixing it I get this error
```
[Error - 9:30:46 PM] SERVER ERROR: definition.map is not a function
TypeError: definition.map is not a function
    at ngDefintionToDefintion (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\server.js:124:32)
    at c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\server.js:151:20
    at logErrors (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\server.js:138:16)
    at c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\server.js:146:66
    at handleRequest (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\node_modules\vscode-jsonrpc\lib\main.js:367:27)
    at processMessageQueue (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\node_modules\vscode-jsonrpc\lib\main.js:257:17)
    at Immediate.setImmediate [as _onImmediate] (c:\Users\stefa\.vscode\extensions\angular.ng-template-0.801.1\server\node_modules\vscode-jsonrpc\lib\main.js:247:13)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
```

**Comment by kyliau** [comment]
@Dunsteer are you using Angular version 9?

**Comment by kyliau** [comment]
I've just published version 0.802.2 that should fix this issue. Please let me know otherwise.

**Comment by Dunsteer** [comment]
I was testing it on Angular version 9 but I downgraded my angular back to version 8 until they publish a stable version.

**Comment by kyliau** [comment]
I made some backwards incompatible change in version 9 that requires the extension to be updated. With the new extension that I've just published, the LS should work with both 8 and 9 now.

**Comment by kyliau** [comment]
Issue fixed.
