### ISSUE TITLE
Can't install the extension

### ISSUE THREAD

**Issue by kuncevic** [angular/vscode-ng-language-service#38]
I have just got an error during installation:
```
1/10/2017 10:05:43 AM - Microsoft VSIX Installer
1/10/2017 10:05:43 AM - -------------------------------------------
1/10/2017 10:05:43 AM - vsixinstaller.exe version:
1/10/2017 10:05:43 AM - 15.0.26014.0 built by: D15REL
1/10/2017 10:05:43 AM - -------------------------------------------
1/10/2017 10:05:43 AM - Command line parameters:
1/10/2017 10:05:43 AM - C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VSIXInstaller.exe,C:\Users\me\Downloads\ngls.vsix
1/10/2017 10:05:43 AM - -------------------------------------------
1/10/2017 10:05:43 AM - Microsoft VSIX Installer
1/10/2017 10:05:43 AM - -------------------------------------------
1/10/2017 10:05:44 AM - Initializing Install...
1/10/2017 10:05:45 AM - Extension Details...
1/10/2017 10:05:45 AM - 	Identifier         : ng-template
1/10/2017 10:05:45 AM - 	Name               : Angular Language Service
1/10/2017 10:05:45 AM - 	Author             : Google
1/10/2017 10:05:45 AM - 	Version            : 0.0.10
1/10/2017 10:05:45 AM - 	Description        : Editor services for Angular templates
1/10/2017 10:05:45 AM - 	Locale             : en-US
1/10/2017 10:05:45 AM - 	MoreInfoURL        : 
1/10/2017 10:05:45 AM - 	InstalledByMSI     : False
1/10/2017 10:05:45 AM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
1/10/2017 10:05:45 AM - 
1/10/2017 10:05:45 AM - 	SignatureState     : Unsigned
1/10/2017 10:05:45 AM - 	Supported Products : 
1/10/2017 10:05:45 AM - 		Microsoft.VisualStudio.Code
1/10/2017 10:05:45 AM - 			Version : 
1/10/2017 10:05:45 AM - 
1/10/2017 10:05:45 AM - 	References         : 
1/10/2017 10:05:45 AM - Signature Details...
1/10/2017 10:05:45 AM - 	Extension is not signed.
1/10/2017 10:05:45 AM - 
1/10/2017 10:05:45 AM - Searching for applicable products...
1/10/2017 10:05:45 AM - Found installed product - Global Location
1/10/2017 10:05:45 AM - Found installed product - ssms
1/10/2017 10:05:45 AM - Found installed product - Visual Studio Community 2017 RC
1/10/2017 10:05:46 AM - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
   at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```
I have VSCode 1.8.1 installed running Windows 7 x64

**Comment by lovetofail** [comment]
From the recent pull request - To install the current experimental version, download the latest `ngls.vsix` file https://github.com/angular/vscode-ng-language-service/releases, then select "Install from VSIX" under the extensions menu to install it.

**Comment by kuncevic** [comment]
@lovetofail yeah it is what I was figuring out early on.  However I think it should do just with double click the way it is doing for visual studio.

**Comment by chuckjaz** [comment]
This is not a problem I can fix as double-click behavior on .vsix files is defined and controlled by Microsoft.
