### ISSUE TITLE
Extension not working and crashing

### ISSUE THREAD

**Issue by RobertDelmatic** [angular/vscode-ng-language-service#400]
The extension does not work at all, for me, in HTML templates, and it keeps crashing. Version 0.802.3
This is the console log:

Search path: c:/work/clientportal/angular/src/app/project/dialogs/project-edit-user-dialog
Config file name: c:/work/clientportal/angular/tsconfig.json
Angular Language Service: 6.0.3
TypeScript: 3.5.3
getTemplateReferences: 5629ms
Add recursive watcher for: c:/work/clientportal/angular
Opened configuration file c:/work/clientportal/angular/tsconfig.json
getTemplateReferences: 0ms
getDiagnostics: 124ms
internal/process/next_tick.js:63
          Reflect.apply(callback, undefined, tock.args);
                  ^

TypeError: Reflect.apply is not a function
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 16:15:39] Connection to server got closed. Server will restart.
[Error - 16:15:39] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:876:25)
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:71:35)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2153:42)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\main.js:151:15)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2140:18)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:226:26)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at IPCMessageReader.fireClose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Search path: c:/work/clientportal/angular/src/app/project/dialogs/project-edit-user-dialog
Config file name: c:/work/clientportal/angular/tsconfig.json
Angular Language Service: 6.0.3
TypeScript: 3.5.3
getTemplateReferences: 5805ms
Add recursive watcher for: c:/work/clientportal/angular
Opened configuration file c:/work/clientportal/angular/tsconfig.json
getTemplateReferences: 0ms
getDiagnostics: 149ms
internal/process/next_tick.js:63
          Reflect.apply(callback, undefined, tock.args);
                  ^

TypeError: Reflect.apply is not a function
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 16:19:16] Connection to server got closed. Server will restart.
[Error - 16:19:16] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:876:25)
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:71:35)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2153:42)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\main.js:151:15)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2140:18)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:226:26)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at IPCMessageReader.fireClose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Search path: c:/work/clientportal/angular/src/app/project/dialogs/project-edit-user-dialog
Config file name: c:/work/clientportal/angular/tsconfig.json
internal/process/next_tick.js:63
          Reflect.apply(callback, undefined, tock.args);
                  ^

TypeError: Reflect.apply is not a function
    at process._tickCallback (internal/process/next_tick.js:63:19)
[Info  - 16:19:28] Connection to server got closed. Server will restart.
[Error - 16:19:28] Request textDocument/definition failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:876:25)
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:71:35)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2153:42)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\main.js:151:15)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2140:18)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:226:26)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at IPCMessageReader.fireClose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
[Error - 16:19:28] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:876:25)
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:71:35)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2153:42)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\main.js:151:15)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2140:18)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:226:26)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at IPCMessageReader.fireClose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
[Error - 16:19:28] Request textDocument/hover failed.
Error: Connection got disposed.
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:876:25)
    at Object.dispose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:71:35)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2153:42)
    at LanguageClient.handleConnectionClosed (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\main.js:151:15)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-languageclient\lib\client.js:2140:18)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at closeHandler (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\main.js:226:26)
    at CallbackList.invoke (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:62:39)
    at Emitter.fire (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\events.js:120:36)
    at IPCMessageReader.fireClose (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:111:27)
    at ChildProcess.constructor.eventEmitter.on (c:\Users\RobertM\.vscode\extensions\angular.ng-template-0.802.3\client\node_modules\vscode-jsonrpc\lib\messageReader.js:213:45)
    at ChildProcess.emit (events.js:187:15)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
Search path: c:/work/clientportal/angular/src/app/project/dialogs/project-edit-user-dialog
Config file name: c:/work/clientportal/angular/tsconfig.json
Angular Language Service: 6.0.3
TypeScript: 3.5.3
getTemplateReferences: 5351ms
Add recursive watcher for: c:/work/clientportal/angular
Opened configuration file c:/work/clientportal/angular/tsconfig.json
getTemplateReferences: 0ms
getDiagnostics: 106ms

**Comment by ayazhafiz** [comment]
Are you opening VSCode in the root directory of your Angular project?

**Comment by andrius-pra** [comment]
Your Angular Language Service is very old. Try package in your repository.
`npm install @angular/language-service --save-dev`
or
`yarn add --dev @angular/language-service`

**Comment by RobertDelmatic** [comment]
Thank you andrius-pra, that was indeed the issue.
