### ISSUE TITLE
"install failed. Element 'Identity' has invalid value for attribute 'Version'

### ISSUE THREAD

**Issue by oocx** [angular/vscode-ng-language-service#450]
I just downloaded the .vsix for v0.900.0-rc.3. When I open it, I get a popup with the error message:

```
Install Failed

The install of '' was not successful for all the selected products. For more information, click on the install log link at the bottom of the dialog. 

Element 'Identity' has invalid value for attribute 'Version'
```
That's in the install log:
```
23.11.2019 23:24:20 - Microsoft VSIX Installer
23.11.2019 23:24:20 - -------------------------------------------
23.11.2019 23:24:20 - vsixinstaller.exe version:
23.11.2019 23:24:20 - 16.3.2099
23.11.2019 23:24:20 - -------------------------------------------
23.11.2019 23:24:20 - Command line parameters:
23.11.2019 23:24:20 - C:\Program Files (x86)\Microsoft Visual Studio\Installer\resources\app\ServiceHub\Services\Microsoft.VisualStudio.Setup.Service\VSIXInstaller.exe,C:\Users\mathi\Downloads\ngls.vsix
23.11.2019 23:24:20 - -------------------------------------------
23.11.2019 23:24:20 - Microsoft VSIX Installer
23.11.2019 23:24:20 - -------------------------------------------
23.11.2019 23:24:23 - Initializing Install...
23.11.2019 23:24:23 - Microsoft.VisualStudio.ExtensionManager.InvalidExtensionManifestException: Element 'Identity' has invalid value for attribute 'Version' ---> System.FormatException: Input string was not in a correct format.
   at System.Version.VersionResult.SetFailure(ParseFailureKind failure, String argument)
   at System.Version.TryParseComponent(String component, String componentName, VersionResult& result, Int32& parsedComponent)
   at System.Version.TryParseVersion(String version, VersionResult& result)
   at System.Version.Parse(String input)
   at System.Version..ctor(String version)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.<>c.<ExtractManifestData>b__67_1(String s)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.VerifyStringValue[T](String value, ErrorInfo info, Func`2 selector, Boolean isRequired, Int32 maxLength, T defaultValue)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ExtractManifestData(PackageManifest manifest)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadPackageManifest(XmlReader reader)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionImpl.ReadManifest(Stream manifestStream)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl.ReadVSIXManifestFromPackage(Stream stream, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.InstallableExtensionImpl..ctor(String path, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath, CultureInfo preferredCulture)
   at Microsoft.VisualStudio.ExtensionManager.ExtensionEngineImpl.CreateInstallableExtension(String extensionPath)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

```

My VS Code version is 1.40.1 (user setup).
I'm using Windows 10 Build 19023.

**Comment by oocx** [comment]
I just found out that it works when I use "install from vsix" instead of just opening the vsix file directly.
