### ISSUE TITLE
The Language server is crashing when templateUrl points to non-existing file

### ISSUE THREAD

**Issue by andrius-pra** [angular/vscode-ng-language-service#469]
**Describe the bug**

The Language server is restarting when templateUrl points to non-existing file.

**To Reproduce**
1. Update to version 0.900.0
2. Open any angular project
4. change template url to non-existing filename.

**Expected behavior**

Expected to get `URL does not point to a valid file` diagnostic message.

**Logs**

1. Console output:
```
[Info  - 22:31:47] Connection to server got closed. Server will restart.
[Info  - 22:31:47] Angular language server process ID: 18316
[Info  - 22:31:47] Using typescript v3.6.4 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 22:31:47] Using @angular/language-service v9.0.0-rc.3 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 22:31:47] Log file: c:\Users\Andrius\AppData\Roaming\Code\logs\20191202T003053\exthost1\Angular.ng-template\nglangsvc.log
[Error - 22:31:52] TypeError: Cannot read property 'attachToProject' of undefined
    at c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129871:32
    at Object.enumerateInsertsAndDeletes (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:2003:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129865:20)
    at ConfiguredProject.Project.updateGraph (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129745:42)
    at ConfiguredProject.updateGraph (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:130316:63)
    at ProjectService.createLoadAndUpdateConfiguredProject (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:131785:25)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:132598:44)
    at ProjectService.openClientFileWithNormalizedPath (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:132652:31)
    at ProjectService.openClientFile (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:132536:29)
    at ProjectService.openClientFile (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\server\index.js:813:32)
[Error - 22:31:52] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'attachToProject' of undefined
[Error - 22:31:52] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Cannot read property 'attachToProject' of undefined
  Code: -32603 
c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129871
                    scriptInfo.attachToProject(_this);
                               ^

TypeError: Cannot read property 'attachToProject' of undefined
    at c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129871:32
    at Object.enumerateInsertsAndDeletes (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:2003:13)
    at ConfiguredProject.Project.updateGraphWorker (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129865:20)
    at ConfiguredProject.Project.updateGraph (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129745:42)
    at ConfiguredProject.updateGraph (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:130316:63)
    at Object.updateProjectIfDirty (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:130674:45)
    at ConfiguredProject.Project.getLanguageService (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\node_modules\typescript\lib\tsserverlibrary.js:129429:28)
    at Session.sendPendingDiagnostics (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\server\index.js:1011:35)
    at Timeout._onTimeout (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\server\index.js:992:19)
    at listOnTimeout (internal/timers.js:531:17)
[Info  - 22:31:52] Connection to server got closed. Server will restart.
```

2. Log file:
```
Info 0    [22:43:37.275] Format host information updated
Info 1    [22:43:37.276] reload projects.
Info 2    [22:43:37.276] Structure before ensureProjectForOpenFiles:
Info 3    [22:43:37.276] Structure after ensureProjectForOpenFiles:
Info 4    [22:43:37.276] Host file extension mappings updated
Info 5    [22:43:37.286] Search path: d:/demo/repro/src/app
Info 6    [22:43:37.287] For info: d:/demo/repro/src/app/app.component.ts :: Config file name: d:/demo/repro/tsconfig.json
Info 7    [22:43:37.288] Opened configuration file d:/demo/repro/tsconfig.json
Info 8    [22:43:37.333] Loading global plugin @angular/language-service
Info 9    [22:43:37.333] Enabling plugin @angular/language-service from candidate paths: c:/Users/Andrius/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js/../../..,c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\server\node_modules\@angular\language-service\bundles\language-service.umd.js
Info 10   [22:43:37.333] Loading @angular/language-service from c:/Users/Andrius/.vscode/extensions/angular.ng-template-0.900.0/node_modules/typescript/lib/tsserverlibrary.js/../../.. (resolved to c:/Users/Andrius/.vscode/extensions/angular.ng-template-0.900.0/node_modules/node_modules)
Info 11   [22:43:37.353] Loading @angular/language-service from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.0\server\node_modules\@angular\language-service\bundles\language-service.umd.js (resolved to c:/Users/Andrius/.vscode/extensions/angular.ng-template-0.900.0/server/node_modules/@angular/language-service/bundles/language-service.umd.js/node_modules)
Info 12   [22:43:37.449] Plugin validation succeded
Info 13   [22:43:37.502] Starting updateGraphWorker: Project: d:/demo/repro/tsconfig.json
```

**Screenshots**

![bug](https://user-images.githubusercontent.com/17968027/69921681-05537d00-149d-11ea-9bb5-99bbe737a4db.gif)

**Additional context**

Related to error from #464

**Comment by kyliau** [comment]
This is fixed by the PR above.
