### ISSUE TITLE
Max call stack size exceeded in StaticSymbolResolver.resolveModule

### ISSUE THREAD

**Issue by blubberbo** [angular/vscode-ng-language-service#593]
I am getting the `The Angular Language Service server crashed 5 times in the last 3 minutes. The server will not be restarted.` message in my vscode. 

The output is the following:
```
[Info  - 5:15:00 PM] Angular language server process ID: 1559
[Info  - 5:15:00 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 5:15:00 PM] Using @angular/language-service v9.0.0-rc.11 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 5:15:00 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200129T171048/exthost1/Angular.ng-template/nglangsvc.log
/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22347
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22552:25)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22325:53)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
[Info  - 5:15:05 PM] Connection to server got closed. Server will restart.
[Info  - 5:15:05 PM] Angular language server process ID: 1560
[Info  - 5:15:05 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 5:15:05 PM] Using @angular/language-service v9.0.0-rc.11 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 5:15:05 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200129T171048/exthost1/Angular.ng-template/nglangsvc.log
/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22347
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22552:25)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22325:53)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
[Info  - 5:15:09 PM] Connection to server got closed. Server will restart.
[Info  - 5:15:10 PM] Angular language server process ID: 1561
[Info  - 5:15:10 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 5:15:10 PM] Using @angular/language-service v9.0.0-rc.11 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 5:15:10 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200129T171048/exthost1/Angular.ng-template/nglangsvc.log
/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22347
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22552:25)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22325:53)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
[Info  - 5:15:14 PM] Connection to server got closed. Server will restart.
[Info  - 5:15:15 PM] Angular language server process ID: 1565
[Info  - 5:15:15 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 5:15:15 PM] Using @angular/language-service v9.0.0-rc.11 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 5:15:15 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200129T171048/exthost1/Angular.ng-template/nglangsvc.log
/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22347
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22552:25)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22325:53)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
[Info  - 5:15:19 PM] Connection to server got closed. Server will restart.
[Info  - 5:15:19 PM] Angular language server process ID: 1566
[Info  - 5:15:19 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 5:15:19 PM] Using @angular/language-service v9.0.0-rc.11 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 5:15:19 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200129T171048/exthost1/Angular.ng-template/nglangsvc.log
/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22347
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22552:25)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22325:53)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.7/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22281:18)
[Error - 5:15:24 PM] Connection to server got closed. Server will not be restarted.
```

**Comment by ayazhafiz** [comment]
Can you provide us with the log file? It’s the fourth line on the console output.

**Comment by blubberbo** [comment]
sure, see the following: [nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4131986/nglangsvc.log)

**Comment by ayazhafiz** [comment]
Strange, the log looks okay. Did you ever observe this error before the latest version of the extension? This might be related to #594.

**Comment by kyliau** [comment]
@blubberbo Do you mind turning on verbose logging and capture the log file again?
It'd allow us to see all dependencies of your project.
If that's ok with you, it can be activated by going to
File > Preferences > Settings > Search 'angular.log' > Pick verbose
Then restart the Angular language service by searching for the command "Restart Angular language server"
Thank you

**Comment by andrius-pra** [comment]
I got similar error: 
![bug](https://user-images.githubusercontent.com/17968027/73491636-bac88100-43b7-11ea-8ead-7463c1c11d3b.gif)
 


```
[Info  - 23:22:41] Angular language server process ID: 88360
[Info  - 23:22:41] Using typescript v3.7.4 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 23:22:41] Using @angular/language-service v9.0.0-rc.11 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 23:22:41] Log file: c:\Users\Andrius\AppData\Roaming\Code\logs\20200130T232239\exthost1\Angular.ng-template\nglangsvc.log
[Error - 23:23:05] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Maximum call stack size exceeded
  Code: -32603 
c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22347
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22552:25)
    at _loop_1 (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22325:53)
    at StaticSymbolResolver._createSymbolsOf (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22281:18)
    at _loop_1 (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22281:18)
    at _loop_1 (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22327:56)
    at StaticSymbolResolver._createSymbolsOf (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22339:25)
    at StaticSymbolResolver.getSymbolsOf (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js:22281:18)
[Info  - 23:23:06] Connection to server got closed. Server will restart.
[Info  - 23:23:06] Angular language server process ID: 86380
[Info  - 23:23:06] Using typescript v3.7.4 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 23:23:06] Using @angular/language-service v9.0.0-rc.11 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 23:23:06] Log file: c:\Users\Andrius\AppData\Roaming\Code\logs\20200130T232239\exthost1\Angular.ng-template\nglangsvc.log
c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:2148
            throw e;
            ^

Error: Debug Failure. False expression.
    at checkChangeRange (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:24816:26)
    at Object.updateSourceFile (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:24446:13)
    at Object.updateSourceFile (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:18297:47)
    at Object.updateLanguageServiceSourceFile (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:130949:44)
    at acquireOrUpdateDocument (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:109281:43)
    at Object.updateDocumentWithKey (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:109247:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:131229:49)
    at tryReuseStructureFromOldProgram (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:95529:28)
    at Object.createProgram (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:95121:30)
    at synchronizeHostData (c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:131151:26)
[Info  - 23:23:18] Connection to server got closed. Server will restart.
[Info  - 23:23:19] Angular language server process ID: 110076
[Info  - 23:23:19] Using typescript v3.7.4 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 23:23:19] Using @angular/language-service v9.0.0-rc.11 from c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 23:23:19] Log file: c:\Users\Andrius\AppData\Roaming\Code\logs\20200130T232239\exthost1\Angular.ng-template\nglangsvc.log
[Error - 23:23:24] Request textDocument/completion failed.
  Message: Request textDocument/completion failed with message: Debug Failure. False expression.
  Code: -32603 
c:\Users\Andrius\.vscode\extensions\angular.ng-template-0.900.7\node_modules\typescript\lib\tsserverlibrary.js:2148
            throw e;
            ^
```

**Comment by blubberbo** [comment]
> @blubberbo Do you mind turning on verbose logging and capture the log file again?
> It'd allow us to see all dependencies of your project.
> If that's ok with you, it can be activated by going to
> File > Preferences > Settings > Search 'angular.log' > Pick verbose
> Then restart the Angular language service by searching for the command "Restart Angular language server"
> Thank you

[Info  - 7:20:22 PM] Angular language server process ID: 787
[Info  - 7:20:22 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 7:20:22 PM] Using @angular/language-service v9.0.0-rc.12 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 7:20:22 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200130T191754/exthost1/Angular.ng-template/nglangsvc.log
[Error - 7:20:26 PM] No config file for /Users/iblubberbo/Documents/GitHub/Lol-Pickem/lol-pickem-app/src/app/team/team.component.html
/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22342
                    finally { if (e_2) throw e_2.error; }
                                       ^

RangeError: Maximum call stack size exceeded
    at StaticSymbolResolver.resolveModule (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22547:25)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22320:53)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22334:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22276:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22322:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22334:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22276:18)
    at _loop_1 (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22322:56)
    at StaticSymbolResolver._createSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22334:25)
    at StaticSymbolResolver.getSymbolsOf (/Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js:22276:18)
[Info  - 7:21:43 PM] Connection to server got closed. Server will restart.
[Info  - 7:21:43 PM] Angular language server process ID: 832
[Info  - 7:21:43 PM] Using typescript v3.7.4 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 7:21:43 PM] Using @angular/language-service v9.0.0-rc.12 from /Users/iblubberbo/.vscode/extensions/angular.ng-template-0.900.8/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 7:21:43 PM] Log file: /Users/iblubberbo/Library/Application Support/Code/logs/20200130T191754/exthost1/Angular.ng-template/nglangsvc.log
[Error - 7:21:47 PM] No config file for /Users/iblubberbo/Documents/GitHub/Lol-Pickem/lol-pickem-app/src/app/app.component.html
[Error - 7:21:48 PM] Request textDocument/hover failed.
  Message: Request textDocument/hover failed with message: Maximum call stack size exceeded
  Code: -32603 

and

[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4137433/nglangsvc.log)

**Comment by kyliau** [comment]
Thank you @andrius-pra for the repro. I was able to replicate the crash on my machine. It looks like it was trying to recursively resolve the symbols from the same file.
