### ISSUE TITLE
Extension not re-enabled after being disabled due to missing core.d.ts

### ISSUE THREAD

**Issue by izio38** [angular/vscode-ng-language-service#693]
**Is your feature request related to a problem? Please describe.**

I have a monorepo project. With 3 services :
  - client : Angular
  - api : NestJs
  - mailer : NestJs

Tree : 
```
.
├── docker-compose.yaml
└── stacks
    ├── api
    ├── client
    └── mailer
```

When I have no opened tabs, and I go to `/client`, everything is fine, ALS is starting fastly and without issues.
If I go to `/mailer/**/*.ts`, ALS is stopping :
```
Disabling language service for h:/workspace/IziBills/stacks/mailer/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
```

If I go back to the `/client` service, the spinner is loading without end and without logs. `Initializing Angular language feature`. I tried to close all tabs when this happens, but nothing changed. It just load in the void.

**Describe the solution you'd like**

I would like Angular language service to work only in my `/client` directory. And I don't want it to initializing again when I'm switching services. Couldn't we make ALS to not stop when it reach a non-angular project, but just ignore all this sub-project directory ?

**Comment by ayazhafiz** [comment]
Can you list the entire output of the Angular language service by going to View > Toggle Output > Angular Language service in the dropdown?

**Comment by izio38** [comment]
I opened vscode when no tabs opened. I went to the Angular project sub-directory. I went to the NestJs project sub-directory. I went back to the Angular project directory.

Note : I didn't let a tab opened while doing this, I just clicked on a project file.

```
[Info  - 23:17:45] Angular language server process ID: 11496
[Info  - 23:17:45] Using typescript v3.7.4 from c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 23:17:45] Using @angular/language-service v9.0.7 from c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 23:17:45] Log file: c:\Users\Izio\AppData\Roaming\Code\logs\20200323T231739\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 23:18:31] Disabling language service for h:/workspace/IziBills/stacks/api/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[Error - 23:18:31] TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at Object.getCompilerOptionsDiagnostics (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:131286:43)
    at ProjectService.sendConfigFileDiagEvent (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:137667:64)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138347:38)
    at ProjectService.openClientFileWithNormalizedPath (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138393:31)
    at ProjectService.openClientFile (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138273:29)
    at ProjectService.openClientFile (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:811:32)
    at Session.onDidOpenTextDocument (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:1055:49)
    at c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:948:47
    at handleNotification (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\vscode-jsonrpc\lib\main.js:502:43)
    at processMessageQueue (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\vscode-jsonrpc\lib\main.js:273:17)
[Error - 23:18:31] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'getOptionsDiagnostics' of undefined
c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:131286
            return __spreadArrays(program.getOptionsDiagnostics(cancellationToken), program.getGlobalDiagnostics(cancellationToken));
                                          ^

TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at Object.getCompilerOptionsDiagnostics (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:131286:43)
    at ProjectService.sendConfigFileDiagEvent (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:137667:64)
    at ProjectService.reloadConfiguredProject (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:137661:22)
    at ConfiguredProject.updateGraph (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:136018:45)
    at updateProjectIfDirty (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:136388:45)
    at c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:136609:25
    at Timeout.ThrottledOperations.run [as _onTimeout] (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:133559:17)
    at listOnTimeout (internal/timers.js:533:17)
    at processTimers (internal/timers.js:475:7)
[Info  - 23:18:31] Connection to server got closed. Server will restart.
[Info  - 23:18:32] Angular language server process ID: 6092
[Info  - 23:18:32] Using typescript v3.7.4 from c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 23:18:32] Using @angular/language-service v9.0.7 from c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 23:18:32] Log file: c:\Users\Izio\AppData\Roaming\Code\logs\20200323T231739\exthost1\Angular.ng-template\nglangsvc.log
[Info  - 23:18:35] Disabling language service for h:/workspace/IziBills/stacks/api/tsconfig.json because it is not an Angular project ('@angular/core/core.d.ts' could not be found). If you believe you are seeing this message in error, please reinstall the packages in your package.json.
[Error - 23:18:35] TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at Object.getCompilerOptionsDiagnostics (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:131286:43)
    at ProjectService.sendConfigFileDiagEvent (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:137667:64)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138347:38)
    at ProjectService.openClientFileWithNormalizedPath (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138393:31)
    at ProjectService.openClientFile (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138273:29)
    at ProjectService.openClientFile (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:811:32)
    at Session.onDidOpenTextDocument (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:1055:49)
    at c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:948:47
    at handleNotification (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\vscode-jsonrpc\lib\main.js:502:43)
    at processMessageQueue (c:\Users\Izio\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\vscode-jsonrpc\lib\main.js:273:17)
[Error - 23:18:35] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'getOptionsDiagnostics' of undefined
```

**Comment by ayazhafiz** [comment]
Cool, thanks. I know what the problem is and will submit a patch soon.

**Comment by ayazhafiz** [comment]
The language server extension is not disabled, but language service features are disabled when a non-Angular project is opened. The reason we do this is because the Angular language service wraps around tsserver, so we do not want to serve possibly-Angular results in a context where only TypeScript is applicable.

**Comment by izio38** [comment]
awesome thanks you.

**Comment by izio38** [comment]
Just to tell you that it's working like a charm !

**Comment by ayazhafiz** [comment]
👍

________________________________
От: izio38 <notifications@github.com>
Отправлено: Friday, March 27, 2020 1:52:16 PM
Кому: angular/vscode-ng-language-service <vscode-ng-language-service@noreply.github.com>
Копия: hafiz <ayaz.hafiz.1@gmail.com>; State change <state_change@noreply.github.com>
Тема: Re: [angular/vscode-ng-language-service] Extension not re-enabled after being disabled due to missing core.d.ts (#693)


Just to tell you that it's working like a charm !
