### ISSUE TITLE
Cannot find config file for tslib, followed by tsserver type error

### ISSUE THREAD

**Issue by RezaRahmati** [angular/vscode-ng-language-service#696]
**Describe the bug**

If the bug is caused or experienced by a particular source code, please provide a minimal
reproduction of that source code.

**To Reproduce**

I noticed recently the extensions is not working intermittently. When  I open the Output window in vscode I see some errors regarding to No Config File for ...

**Expected behavior**

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
```
[Info  - 10:26:53 PM] Angular language server process ID: 15636
[Info  - 10:26:53 PM] Using typescript v3.7.4 from c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 10:26:53 PM] Using @angular/language-service v9.0.7 from c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 10:26:53 PM] Log file: c:\Users\RezaR\AppData\Roaming\Code\logs\20200320T214651\exthost4\Angular.ng-template\nglangsvc.log
[Error - 10:29:55 PM] No config file for c:\Users\RezaR\AppData\Local\Programs\Microsoft VS Code\resources\app\extensions\node_modules\typescript\lib\lib.es5.d.ts
[Error - 10:37:33 PM] TypeError: Cannot read property 'getOptionsDiagnostics' of undefined
    at Object.getCompilerOptionsDiagnostics (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:131286:43)
    at ProjectService.sendConfigFileDiagEvent (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:137667:64)
    at ProjectService.assignProjectToOpenedScriptInfo (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138347:38)
    at ProjectService.openClientFileWithNormalizedPath (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138393:31)
    at ProjectService.openClientFile (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js:138273:29)
    at ProjectService.openClientFile (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:811:32)
    at Session.onDidOpenTextDocument (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:1055:49)
    at c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\index.js:948:47
    at handleNotification (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\vscode-jsonrpc\lib\main.js:502:43)
    at processMessageQueue (c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\vscode-jsonrpc\lib\main.js:273:17)
[Error - 10:37:33 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'getOptionsDiagnostics' of undefined
```
another one
```
[Info  - 4:27:41 AM] Angular language server process ID: 21636
[Info  - 4:27:41 AM] Using typescript v3.7.4 from c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\node_modules\typescript\lib\tsserverlibrary.js
[Info  - 4:27:41 AM] Using @angular/language-service v9.0.7 from c:\Users\RezaR\.vscode\extensions\angular.ng-template-0.900.18\server\node_modules\@angular\language-service\bundles\language-service.umd.js
[Info  - 4:27:41 AM] Log file: c:\Users\RezaR\AppData\Roaming\Code\logs\20200320T214651\exthost6\Angular.ng-template\nglangsvc.log
[Error - 4:28:02 AM] No config file for c:\projects\xy\xybot-newadmin\admin\bot-studio\src\app\bot\intent\parameters\intent-parameters-list\intent-parameters-list.component.html

```
2. Log file (Path is printed to the console output at startup)

[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4364572/nglangsvc.log)

[nglangsvc.log](https://github.com/angular/vscode-ng-language-service/files/4364912/nglangsvc.log)

**Screenshots**

**Additional context**
vscode: 1.43.1 
Angular language service: 0.900.18

**Comment by ayazhafiz** [comment]
Could you list what your tsconfig.json is in the first example? Also, is `typescript.tsdk` defined in your VSCode settings? If so, what is the value?

The second example of the config file not found for HTML files should not be a problem (the language service still works in that case, right?) but we will look into removing the error.

**Comment by RezaRahmati** [comment]
@ayazhafiz I have had 2 projects open I add tsconfig for both

```
{
  "compilerOptions": {
    "module": "commonjs",

    "declaration": true,
    "removeComments": true,
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,

    "noImplicitReturns": true,
    "noUnusedLocals": true,
    "outDir": "dist",
    "sourceMap": true,
    "strict": true,
    "target": "es2017",
    "strictNullChecks": false,
    "noImplicitAny": false
  },
  "compileOnSave": true,
  "include": [
    "src"
  ],
  "exclude": ["node_modules"]
}
```

and 

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "baseUrl": "./",
        "outDir": "./dist/out-tsc",
        "sourceMap": true,
        "declaration": false,
        "module": "esnext",
        "moduleResolution": "node",
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "importHelpers": true,
        "target": "es2015",
        "typeRoots": [
            "node_modules/@types"
        ],
        "lib": [
            "es2018",
            "dom"
        ],
        "paths": {
            "jszip": [
                "node_modules/jszip/dist/jszip.min.js"
            ]
        }
    }
}

```

> (the language service still works in that case, right?)

For the second error, I only had one vscode open and then it stopped working, this why I added Output of that in my bug report

**Comment by ayazhafiz** [comment]
Cool, thanks. I think this has the same root cause as #693

**Comment by RezaRahmati** [comment]
> Cool, thanks. I think this has the same root cause as #693

Thanks, so we will get an update very soon?

**Comment by ayazhafiz** [comment]
Yes; sorry, I had to finish up work. The PR above should fix this.
