### ISSUE TITLE
ng-language-service not working for TypeScript 3.9.1-rc

### ISSUE THREAD

**Issue by xiaoxiangmoe** [angular/vscode-ng-language-service#754]

**Comment by ayazhafiz** [comment]
Can you provide more details? Is your project on Angular 10 or is the language service package you are using on Angular 10?

**Comment by xiaoxiangmoe** [comment]
I'm using latest `Angular Language Service` VSCode extension and Angular 10.

**Comment by ayazhafiz** [comment]
I tried this, the language service extension is enabled and working for me.

Can you list the output of the Angular Language Service extension? (View > Output > Angular Language Service)

**Comment by xiaoxiangmoe** [comment]
Here is my output:
<details>
[Info  - 10:35:50 AM] Angular language server process ID: 48973
[Info  - 10:35:50 AM] Using typescript v3.9.0-dev.20200422 from /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 10:35:50 AM] Using @angular/language-service v9.1.3 from /Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 10:35:50 AM] Log file: /Users/zhaojinxiang/Library/Application Support/Code/logs/20200423T155449/exthost8/Angular.ng-template/nglangsvc.log
[Info  - 10:35:57 AM] Enabling language service for /Users/zhaojinxiang/yfd/conan-live-doctor/tsconfig.json.
[Error - 1:11:47 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/common/http/http.d.ts
[Error - 3:25:25 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/i18n/languages/zh_CN.d.ts
[Error - 3:28:24 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/forms/forms.d.ts
[Error - 5:19:45 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/common/http/http.d.ts
[Error - 5:20:04 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/common/http/http.d.ts
[Error - 5:22:46 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:25:41 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/core/core.d.ts
[Error - 5:28:14 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:35:56 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:35:59 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:40:33 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/core/util/check.d.ts
[Error - 5:40:34 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/core/util/check.d.ts
[Error - 5:40:34 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/ng-zorro-antd.d.ts
[Error - 5:40:36 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/core/util/check.d.ts
[Error - 5:40:37 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/core/util/check.d.ts
[Error - 5:40:37 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/core/types/indexable.d.ts
[Error - 5:40:59 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:45:19 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/rxjs/operators/index.d.ts
[Error - 5:45:20 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/rxjs/operators/index.d.ts
[Error - 5:45:32 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 4:08:01 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 4:10:28 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 4:16:10 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 4:16:11 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 4:16:13 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 4:37:15 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/ng-zorro-antd/core/util/check.d.ts
[Error - 5:24:05 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/forms/forms.d.ts
[Error - 5:26:48 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:26:53 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:34:51 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/lib.es5.d.ts
[Error - 5:50:53 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/rxjs/internal/operators/map.d.ts
[Error - 5:50:53 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/rxjs/internal/Observable.d.ts
[Error - 5:50:54 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 5:50:55 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/router/router.d.ts
[Error - 6:12:18 PM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/rxjs/internal/Observable.d.ts
[Error - 12:41:13 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/core/core.d.ts
[Error - 12:43:07 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/@angular/core/core.d.ts
[Error - 11:37:15 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/lib.dom.d.ts
[Error - 11:37:17 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/lib.dom.d.ts
[Info  - 11:42:57 AM] Enabling language service for /Users/zhaojinxiang/yfd/conan-live-doctor/tsconfig.json.
/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30345
                finally { if (e_1) throw e_1.error; }
                                   ^

TypeError: Cannot read property 'kind' of undefined
    at getConditionalFlowTypeOfType (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:45318:28)
    at getTypeFromTypeNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:47204:20)
    at getTypeOfNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:67085:40)
    at Object.getTypeAtLocation (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:35142:31)
    at getTsTypeFromBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:28521:28)
    at TypeScriptSymbolQuery.getBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27688:28)
    at getEventDeclaration (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26753:30)
    at getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26778:21)
    at ExpressionDiagnosticsVisitor.getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26543:87)
    at ExpressionDiagnosticsVisitor.diagnoseExpression (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26860:30)
[Info  - 11:43:00 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:00 AM] Angular language server process ID: 21089
[Info  - 11:43:00 AM] Using typescript v3.9.0-dev.20200426 from /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 11:43:00 AM] Using @angular/language-service v9.1.3 from /Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 11:43:00 AM] Log file: /Users/zhaojinxiang/Library/Application Support/Code/logs/20200423T155449/exthost8/Angular.ng-template/nglangsvc.log
[Info  - 11:43:08 AM] Enabling language service for /Users/zhaojinxiang/yfd/conan-live-doctor/tsconfig.json.
[Error - 11:43:08 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/projects/conan-live-doctor/src/app/pages/pc-student2/pc-student.component.html
/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30345
                finally { if (e_1) throw e_1.error; }
                                   ^

TypeError: Cannot read property 'kind' of undefined
    at getConditionalFlowTypeOfType (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:45452:28)
    at getTypeFromTypeNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:47338:20)
    at getTypeOfNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:67220:40)
    at Object.getTypeAtLocation (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:35184:31)
    at getTsTypeFromBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:28521:28)
    at TypeScriptSymbolQuery.getBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27688:28)
    at getEventDeclaration (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26753:30)
    at getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26778:21)
    at ExpressionDiagnosticsVisitor.getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26543:87)
    at ExpressionDiagnosticsVisitor.diagnoseExpression (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26860:30)
[Info  - 11:43:10 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:10 AM] Angular language server process ID: 21099
[Info  - 11:43:10 AM] Using typescript v3.9.0-dev.20200426 from /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 11:43:10 AM] Using @angular/language-service v9.1.3 from /Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 11:43:10 AM] Log file: /Users/zhaojinxiang/Library/Application Support/Code/logs/20200423T155449/exthost8/Angular.ng-template/nglangsvc.log
[Info  - 11:43:16 AM] Enabling language service for /Users/zhaojinxiang/yfd/conan-live-doctor/tsconfig.json.
[Error - 11:43:16 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/projects/conan-live-doctor/src/app/pages/pc-student2/pc-student.component.html
/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30345
                finally { if (e_1) throw e_1.error; }
                                   ^

TypeError: Cannot read property 'kind' of undefined
    at getConditionalFlowTypeOfType (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:45452:28)
    at getTypeFromTypeNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:47338:20)
    at getTypeOfNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:67220:40)
    at Object.getTypeAtLocation (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:35184:31)
    at getTsTypeFromBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:28521:28)
    at TypeScriptSymbolQuery.getBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27688:28)
    at getEventDeclaration (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26753:30)
    at getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26778:21)
    at ExpressionDiagnosticsVisitor.getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26543:87)
    at ExpressionDiagnosticsVisitor.diagnoseExpression (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26860:30)
[Info  - 11:43:18 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:18 AM] Angular language server process ID: 21101
[Info  - 11:43:18 AM] Using typescript v3.9.0-dev.20200426 from /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 11:43:18 AM] Using @angular/language-service v9.1.3 from /Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 11:43:18 AM] Log file: /Users/zhaojinxiang/Library/Application Support/Code/logs/20200423T155449/exthost8/Angular.ng-template/nglangsvc.log
[Info  - 11:43:24 AM] Enabling language service for /Users/zhaojinxiang/yfd/conan-live-doctor/tsconfig.json.
[Error - 11:43:24 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/projects/conan-live-doctor/src/app/pages/pc-student2/pc-student.component.html
/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30345
                finally { if (e_1) throw e_1.error; }
                                   ^

TypeError: Cannot read property 'kind' of undefined
    at getConditionalFlowTypeOfType (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:45452:28)
    at getTypeFromTypeNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:47338:20)
    at getTypeOfNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:67220:40)
    at Object.getTypeAtLocation (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:35184:31)
    at getTsTypeFromBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:28521:28)
    at TypeScriptSymbolQuery.getBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27688:28)
    at getEventDeclaration (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26753:30)
    at getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26778:21)
    at ExpressionDiagnosticsVisitor.getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26543:87)
    at ExpressionDiagnosticsVisitor.diagnoseExpression (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26860:30)
[Info  - 11:43:26 AM] Connection to server got closed. Server will restart.
[Info  - 11:43:27 AM] Angular language server process ID: 21103
[Info  - 11:43:27 AM] Using typescript v3.9.0-dev.20200426 from /Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js
[Info  - 11:43:27 AM] Using @angular/language-service v9.1.3 from /Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 11:43:27 AM] Log file: /Users/zhaojinxiang/Library/Application Support/Code/logs/20200423T155449/exthost8/Angular.ng-template/nglangsvc.log
[Info  - 11:43:32 AM] Enabling language service for /Users/zhaojinxiang/yfd/conan-live-doctor/tsconfig.json.
[Error - 11:43:32 AM] No config file for /Users/zhaojinxiang/yfd/conan-live-doctor/projects/conan-live-doctor/src/app/pages/pc-student2/pc-student.component.html
/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30345
                finally { if (e_1) throw e_1.error; }
                                   ^

TypeError: Cannot read property 'kind' of undefined
    at getConditionalFlowTypeOfType (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:45452:28)
    at getTypeFromTypeNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:47338:20)
    at getTypeOfNode (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:67220:40)
    at Object.getTypeAtLocation (/Users/zhaojinxiang/yfd/conan-live-doctor/node_modules/typescript/lib/tsserverlibrary.js:35184:31)
    at getTsTypeFromBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:28521:28)
    at TypeScriptSymbolQuery.getBuiltinType (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27688:28)
    at getEventDeclaration (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26753:30)
    at getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26778:21)
    at ExpressionDiagnosticsVisitor.getExpressionScope (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26543:87)
    at ExpressionDiagnosticsVisitor.diagnoseExpression (/Users/zhaojinxiang/.vscode/extensions/angular.ng-template-0.901.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26860:30)
[Error - 11:43:34 AM] Connection to server got closed. Server will not be restarted.
</details>

**Comment by ayazhafiz** [comment]
I’ll check more later, but this might be the same issue as in #594. Does the issue go away if you lower the TypeScript version to 3.8?

**Comment by xiaoxiangmoe** [comment]
If I lower the TypeScript version to 3.8, It works.

**Comment by ayazhafiz** [comment]
Is `typescript.tsdk` set in your project or global settings? I think this is the problem. If the TypeScript path is specified there, then the language service extension will use that TypeScript version, which may have an API that is different from the API expected by the language service, leading to these errors.

**Comment by xiaoxiangmoe** [comment]
Thanks, fixed.
