### ISSUE TITLE
SERVER ERROR: Cannot read property 'token' of undefined

### ISSUE THREAD

**Issue by hccampos** [angular/vscode-ng-language-service#76]
Getting this right after opening a project and hovering over a template:

```
Config file name: /home/hugo/pix4d/spa/src/tsconfig.json
Angular Language Service: 4.1.0-beta.0
TypeScript: 2.1.6
SERVER ERROR: Cannot read property 'token' of undefined
TypeError: Cannot read property 'token' of undefined
    at /home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:30584:33
    at Array.forEach (native)
    at CompileMetadataResolver._getProvidersMetadata (/home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:30551:19)
    at /home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:30128:63
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:30119:49)
    at addNgModule (/home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:38695:58)
    at /home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:38706:14
    at Array.forEach (native)
    at _createNgModules (/home/hugo/pix4d/spa/node_modules/@angular/language-service/bundles/language-service.umd.js:38705:26)
[Error - 10:07:38 AM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'token' of undefined
```

I have the 4.1.0-beta.0 language in the package.json, not sure that is related. Furthermore, this happens both in VSCode Stable and Insiders.

OS: Ubuntu 16.10

**Comment by chuckjaz** [comment]
Can you try this with `0.1.3` of the language service as well as the `4.1.0-beta.1`?
