### ISSUE TITLE
Language service doesn't work at all: Cannot read property 'kind' of undefined

### ISSUE THREAD

**Issue by tonivj5** [angular/vscode-ng-language-service#797]
**Describe the bug**

Language service doesn't work at all. `tsserverlibrary` throws an error and extension never start. And consume a lot of CPU.

**To Reproduce**

**Expected behavior**

it works

**Logs**

Please attach two logs:

1. Console output (Go to toolbar --> View --> Output, and copy the contents)
```
[Info  - 14:29:20] Using @angular/language-service v9.1.9 from /home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js
[Info  - 14:29:20] Log file: /home/yo/.config/Code/logs/20200528T125828/exthost1/Angular.ng-template/nglangsvc.log
[Info  - 14:29:27] Enabling language service for /home/yo/Proyectos/my-project/apps/app/tsconfig.json.
/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:30390
                finally { if (e_1) throw e_1.error; }
                                   ^

TypeError: Cannot read property 'kind' of undefined
    at getConditionalFlowTypeOfType (/home/yo/Proyectos/my-project/node_modules/typescript/lib/tsserverlibrary.js:45510:28)
    at getTypeFromTypeNode (/home/yo/Proyectos/my-project/node_modules/typescript/lib/tsserverlibrary.js:47396:20)
    at getTypeOfNode (/home/yo/Proyectos/my-project/node_modules/typescript/lib/tsserverlibrary.js:67279:40)
    at Object.getTypeAtLocation (/home/yo/Proyectos/my-project/node_modules/typescript/lib/tsserverlibrary.js:35196:31)
    at getTsTypeFromBuiltinType (/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:28433:28)
    at TypeScriptSymbolQuery.getBuiltinType (/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:27600:28)
    at getEventDeclaration (/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26668:30)
    at getExpressionScope (/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26693:21)
    at ExpressionDiagnosticsVisitor.getExpressionScope (/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26458:87)
    at ExpressionDiagnosticsVisitor.diagnoseExpression (/home/yo/.vscode/extensions/angular.ng-template-0.901.9/server/node_modules/@angular/language-service/bundles/language-service.umd.js:26775:30)
[Error - 14:29:29] Connection to server got closed. Server will not be restarted.
```
2. Log file (Path is printed to the console output at startup)
Nothing anormal. Only initialization log.

**Screenshots**

**Additional context**

If I change this code:
![image](https://user-images.githubusercontent.com/7110786/83141608-447f2580-a0f0-11ea-939b-e7b8e6748b0a.png)
to this code (`&& node.parent`):
![image](https://user-images.githubusercontent.com/7110786/83141667-5e206d00-a0f0-11ea-80d9-20685efeb92a.png)
It works like a charm.

I don't know if it's a problem from `tsserver` or `ng language server`

**Comment by tonivj5** [comment]
I have just see that @c0dybrown has commented about this issue here https://github.com/angular/vscode-ng-language-service/issues/793#issuecomment-635299761

**Comment by ayazhafiz** [comment]
What version of TS is being used?

**Comment by tonivj5** [comment]
You made me think, I have downgraded to `3.8.3` and it seems it works. I was using `3.9.3` :cry:

**Comment by ayazhafiz** [comment]
Yeah, please see https://github.com/angular/vscode-ng-language-service#versioning. Until the extension and the language service are on 3.9 it won’t work. But I think we can update to 3.9 now.

**Comment by ayazhafiz** [comment]
I spoke too soon, looks like 3.9 will be in Ng 10

**Comment by tonivj5** [comment]
Yeah, thanks for the hint. I also was too fast to upgrade to `3.9` :laughing:

If you think this issue should hold open for the future ng 10, cool, otherwise you can close it :sweat_smile:

**Comment by ayazhafiz** [comment]
TS updates happen automatically on our end :-)

Thanks for the report, closing as resolved.
