### ISSUE TITLE
Angular Language Service extension not working

### ISSUE THREAD

**Issue by Cammisuli** [angular/vscode-ng-language-service#85]
Recently I've been getting a lot of errors where the language service is saying that it expected styles for be an array of strings. 
```
Search path: c:/Development/git/ngui/WWW/portals/console/app/controls/device-overview/device-logs/device-logs-grid
Config file name: c:/Development/git/ngui/tsconfig.json
Angular Language Service: 4.1.0-beta.0-96aa236
TypeScript: 2.1.6
SERVER ERROR: Expected 'styles' to be an array of strings.
Error: Expected 'styles' to be an array of strings.
    at assertArrayOfStrings (C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:19525:19)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:29976:13)
    at CompileMetadataResolver._getEntryComponentMetadata (C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:30678:45)
    at C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:30261:110
    at Array.map (native)
    at CompileMetadataResolver.getNgModuleMetadata (C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:30261:73)
    at addNgModule (C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:38725:58)
    at C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:38736:14
    at Array.forEach (native)
    at _createNgModules (C:\Users\jcammisuli\.vscode-insiders\extensions\Angular.ng-template-0.1.3\server\node_modules\@angular\language-service\bundles\language-service.umd.js:38735:26)
[Error - 9:38:29 AM] Notification handler 'textDocument/didOpen' failed with message: Expected 'styles' to be an array of strings.
```
I did a global search and found no occurrences of components with `styleUrls` being just a string.

Other times, when I don't get the above error, I get the following:
```
Search path: c:/Development/git/ngui/WWW/shared/controls/dialogs/pop-up
Config file name: c:/Development/git/ngui/tsconfig.json
Angular Language Service: 4.1.0-beta.0-96aa236
TypeScript: 2.1.6
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
[Info  - 9:39:44 AM] Connection to server got closed. Server will restart.
```

Using the following:
Windows 10
VSCode Version 1.11.2

**Comment by Cammisuli** [comment]
Solved the problem. There was an old component that was still using `styles: [ require('./style.scss') ]` from a looooooooong time ago.

**Comment by hccampos** [comment]
Still a good catch, @Cammisuli. The language service should be resilient to bad/old code. I think you should re-open it.
