### ISSUE TITLE
Can't get it to work...

### ISSUE THREAD

**Issue by yanfosec** [angular/vscode-ng-language-service#90]
I am trying to edit html templates in the latest versions of Angular and TypeScript, and the extension is not working.  I have to select Angular Template manually (from HTML), and all the coloring disappears with intellisense not working either.

Do I have to do anything more after installing it in VS Code?

Rinning VSCode Version 1.11.2 on macOS Sierra

**Comment by blackholegalaxy** [comment]
Try disabling all other extensions. Keep ALS on.

**Comment by yanfosec** [comment]
Did that, same problem.

**Comment by fxck** [comment]
What typescript version?

**Comment by yanfosec** [comment]
2.2.2

**Comment by yanfosec** [comment]
 ~/ tsc -v
Version 2.2.2

**Comment by fxck** [comment]
https://github.com/angular/vscode-ng-language-service/issues/43

**Comment by realappie** [comment]
I can't get it to work either.
```
[Error - 11:27:11 AM] Notification handler 'textDocument/didSave' failed with message: Cannot read property 'length' of undefined
Search path: /Users/abdel/code/eva-grid-builder/src/app/page-details
Config file name: /Users/abdel/code/eva-grid-builder/tsconfig.json
Angular Language Service: 4.1.0
TypeScript: 2.1.6
SERVER ERROR: Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at StaticSymbolResolver.resolveSymbol (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:40217:33)
    at StaticReflector.getTypeMetadata (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:40028:67)
    at StaticReflector.annotations (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:39458:55)
    at DirectiveResolver.isDirective (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:29705:61)
    at CompileMetadataResolver._getTypeDescriptor (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:30768:37)
    at /Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:30639:78
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:30622:49)
    at addNgModule (/Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:39185:58)
    at /Users/abdel/code/eva-grid-builder/node_modules/@angular/language-service/bundles/language-service.umd.js:39196:14
[Error - 11:28:50 AM] Notification handler 'textDocument/didSave' failed with message: Cannot read property 'length' of undefined
````

**Comment by krokofant** [comment]
For me the intellisense start working but I'm missing color highligthing and formatting

**Comment by VladimirMakaev** [comment]
I can't get it working when using with Angular 2 Advanced Seed project. https://github.com/NathanWalker/angular-seed-advanced

The error I'm getting:
```
Search path: /Users/vladimir/Projects/angular-seed-advanced/src/client/app/components/about
Config file name: /Users/vladimir/Projects/angular-seed-advanced/src/client/tsconfig.json
Angular Language Service: 4.1.0-beta.0-96aa236
TypeScript: 2.1.6
SERVER ERROR: Cannot read property 'map' of undefined
TypeError: Cannot read property 'map' of undefined
    at Evaluator.evaluateNode (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:42680:54)
    at _loop_1 (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:43435:57)
    at /Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:43495:25
    at visitEachNode (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/typescript/lib/typescript.js:13888:30)
    at Object.forEachChild (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/typescript/lib/typescript.js:14059:24)
    at MetadataCollector.getMetadata (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:43310:14)
    at ReflectorHost.CompilerHost.getMetadataFor (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:43908:51)
    at StaticSymbolResolver.getModuleMetadata (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:40131:62)
    at StaticSymbolResolver._createSymbolsOf (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:39935:46)
    at StaticSymbolResolver.getSymbolsOf (/Users/vladimir/.vscode/extensions/Angular.ng-template-0.1.3/server/node_modules/@angular/language-service/bundles/language-service.umd.js:39916:14)
[Error - 11:36:47 PM] Notification handler 'textDocument/didOpen' failed with message: Cannot read property 'map' of undefined
```

**Comment by realappie** [comment]
Seems to be working now for me.

**Comment by chuckjaz** [comment]
This should now work in 0.1.4. If not, try deleting `@angular/language-service` from the project's `node_modules` and to for the plugin to use the bundled version of the language service.
